# Sensor Rankings
## FloodNet NYC Tutorial
Author: Mark Bauer

# Summary
TBD

# Table of Contents
TBD

# Import Libraries

In [1]:
# libraries
import numpy as np
import pandas as pd
import polars as pl
import duckdb
from typing import Iterable, Optional
import ast

# Load and Inspect Data
For a more robust approach to inspecting the data, please refer to notebook 01-load-inspect.ipynb.

In [2]:
# list files in data directory
%ls data

Flood Events_Data Dictionary.xlsx
Floodnet_Open_Data_-_Data_Description_03.05.2026.pdf
flood-events.csv
metadata.csv

In [3]:
# read in flood sensor deployments as dataframe
metadata_path = "data/metadata.csv"
metadata_df = pl.read_csv(metadata_path, try_parse_dates=True)

# inspect the shape of the data
n_rows, n_columns = metadata_df.shape
print("Metadata:")
print(f"Number of rows: {n_rows}")
print(f"Number of columns: {n_columns}")

# read in flood events as dataframe
events_path = "data/flood-events.csv"
events_df = pl.read_csv(events_path, infer_schema_length=100000, try_parse_dates=True)

# inspect the shape of the data
n_rows, n_columns = events_df.shape
print("\nFlood Events:")
print(f"Number of rows: {n_rows:,}")
print(f"Number of columns: {n_columns}")

Metadata:
Number of rows: 371
Number of columns: 16

Flood Events:
Number of rows: 1,887
Number of columns: 13

# Join Sensor Metadata and Flood Events Datasets

In [4]:
# merge flood sensor events with sensor metadata
merged_df = events_df.join(
    metadata_df.drop("sensor_name"),
    on="sensor_id",
    how="left",  # keep all events, even if metadata is missing
)

# inspect the shape of the merged data
n_rows, n_columns = merged_df.shape
print(f"Number of rows of merged df: {n_rows:,}")
print(f"Number of columns: {n_columns}")

# events without matching metadata
missing_meta_count = merged_df["sensor_id"].null_count()
print(f"Events without matching sensor metadata: {missing_meta_count}\n")

# preview the first few rows
merged_df.head()

Number of rows of merged df: 1,887
Number of columns: 27
Events without matching sensor metadata: 0

shape: (5, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sensor_na ┆ sensor_id ┆ flood_sta ┆ flood_end ┆ … ┆ latitude  ┆ longitude ┆ lowest_po ┆ location │
│ me        ┆ ---       ┆ rt_time   ┆ _time     ┆   ┆ ---       ┆ ---       ┆ int_heigh ┆ ---      │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ t_delta_i ┆ str      │
│ str       ┆           ┆ datetime[ ┆ datetime[ ┆   ┆           ┆           ┆ nch…      ┆          │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q - Beach ┆ Q-beach-8 ┆ 2023-10-3 ┆ 2023-10-3 ┆ … ┆ 40.59136  ┆ -73.80996 ┆ 8.27      ┆ POINT    │
│ 84 St     ┆ 4-st-0me6 ┆ 0         ┆ 0         ┆   ┆           ┆           ┆           ┆ (-73.809 │
│           ┆ 80        ┆ 12:00:39  ┆ 16:38:19  ┆   ┆           ┆           ┆           ┆ 96 40.59 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 136)     │
│ BX - 1st  ┆ BX-1st-st ┆ 2025-04-2 ┆ 2025-04-2 ┆ … ┆ 40.812851 ┆ -73.88104 ┆ 3.62      ┆ POINT    │
│ St/Avenue ┆ -avenue-a ┆ 6         ┆ 7         ┆   ┆           ┆ 3         ┆           ┆ (-73.881 │
│ A         ┆ -1zby90   ┆ 23:17:20  ┆ 11:55:34  ┆   ┆           ┆           ┆           ┆ 043 40.8 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 12851)   │
│ Q - Beach ┆ Q-beach-3 ┆ 2024-02-0 ┆ 2024-02-0 ┆ … ┆ 40.596618 ┆ -73.76780 ┆ 6.97      ┆ POINT    │
│ 35        ┆ 5-st-beac ┆ 9         ┆ 9         ┆   ┆           ┆ 8         ┆           ┆ (-73.767 │
│ St/Beach  ┆ h-channel ┆ 11:41:01  ┆ 13:20:57  ┆   ┆           ┆           ┆           ┆ 808 40.5 │
│ Channel … ┆ -dr…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 96618)   │
│ BX -      ┆ BX-w-234t ┆ 2025-08-2 ┆ 2025-08-2 ┆ … ┆ 40.88326  ┆ -73.90585 ┆ 4.09      ┆ POINT    │
│ Tibbett   ┆ h-st-tibb ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆ (-73.905 │
│ Ave/W     ┆ ett-ave-2 ┆ 21:05:19  ┆ 00:46:19  ┆   ┆           ┆           ┆           ┆ 85 40.88 │
│ 234th St  ┆ cak…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 326)     │
│ Q -       ┆ Q-davenpo ┆ 2024-01-1 ┆ 2024-01-1 ┆ … ┆ 40.653387 ┆ -73.83055 ┆ 6.97      ┆ POINT    │
│ Davenport ┆ rt-ct-1-0 ┆ 0         ┆ 0         ┆   ┆           ┆ 9         ┆           ┆ (-73.830 │
│ Ct 1      ┆ 7zks0     ┆ 00:39:25  ┆ 02:30:40  ┆   ┆           ┆           ┆           ┆ 559 40.6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 53387)   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# inspect column information and data types
merged_df.schema

Schema([('sensor_name', String),
        ('sensor_id', String),
        ('flood_start_time', Datetime(time_unit='us', time_zone=None)),
        ('flood_end_time', Datetime(time_unit='us', time_zone=None)),
        ('max_depth_inches', Float64),
        ('onset_time_mins', Float64),
        ('drain_time_mins', Float64),
        ('duration_mins', Float64),
        ('duration_above_4_inches_mins', Float64),
        ('duration_above_12_inches_mins', Float64),
        ('duration_above_24_inches_mins', Float64),
        ('flood_profile_depth_inches', String),
        ('flood_profile_time_secs', String),
        ('date_installed', Datetime(time_unit='us', time_zone=None)),
        ('tidally_influenced', String),
        ('date_removed', Datetime(time_unit='us', time_zone=None)),
        ('street_name', String),
        ('borough', String),
        ('zipcode', Int64),
        ('community_board', Int64),
        ('council_district', String),
        ('census_tract', Int64),
        ('nta', String),
        ('latitude', Float64),
        ('longitude', Float64),
        ('lowest_point_height_delta_inches', Float64),
        ('location', String)])

# Data Cleaning
Converting dates to datetime format.

In [6]:
# convert date columns to datetime
merged_df = merged_df.with_columns(
    pl.col("flood_start_time")
        .dt.convert_time_zone(time_zone='America/New_York')
        .alias("flood_start_time_est"),
    pl.col("flood_end_time")
        .dt.convert_time_zone(time_zone='America/New_York')
        .alias("flood_end_time_est")
)

# preview new dtypes
cols =  [
    'flood_start_time',
    'flood_end_time',
    'flood_start_time_est',
    'flood_end_time_est',
]

merged_df.select(cols).head()

shape: (5, 4)
┌─────────────────────┬─────────────────────┬───────────────────────────┬──────────────────────────┐
│ flood_start_time    ┆ flood_end_time      ┆ flood_start_time_est      ┆ flood_end_time_est       │
│ ---                 ┆ ---                 ┆ ---                       ┆ ---                      │
│ datetime[μs]        ┆ datetime[μs]        ┆ datetime[μs,              ┆ datetime[μs,             │
│                     ┆                     ┆ America/New_York]         ┆ America/New_York]        │
╞═════════════════════╪═════════════════════╪═══════════════════════════╪══════════════════════════╡
│ 2023-10-30 12:00:39 ┆ 2023-10-30 16:38:19 ┆ 2023-10-30 08:00:39 EDT   ┆ 2023-10-30 12:38:19 EDT  │
│ 2025-04-26 23:17:20 ┆ 2025-04-27 11:55:34 ┆ 2025-04-26 19:17:20 EDT   ┆ 2025-04-27 07:55:34 EDT  │
│ 2024-02-09 11:41:01 ┆ 2024-02-09 13:20:57 ┆ 2024-02-09 06:41:01 EST   ┆ 2024-02-09 08:20:57 EST  │
│ 2025-08-20 21:05:19 ┆ 2025-08-21 00:46:19 ┆ 2025-08-20 17:05:19 EDT   ┆ 2025-08-20 20:46:19 EDT  │
│ 2024-01-10 00:39:25 ┆ 2024-01-10 02:30:40 ┆ 2024-01-09 19:39:25 EST   ┆ 2024-01-09 21:30:40 EST  │
└─────────────────────┴─────────────────────┴───────────────────────────┴──────────────────────────┘

# Sensor Rankings

# 1) Max Flood Depth
## 1.1 Top 10 Flood Events by Maximum Flood Depth. 
Rankings can have repeated sensors, as table is ranked by events.

In [7]:
sql = """
    SELECT
        sensor_name,
        flood_start_time_est,
        flood_end_time_est,
        max_depth_inches,
        duration_mins,
        tidally_influenced,
        street_name,
        borough
    FROM merged_df
    ORDER BY max_depth_inches DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬──────────┐
│ sensor_nam ┆ flood_star ┆ flood_end_ ┆ max_depth_ ┆ duration_ ┆ tidally_i ┆ street_na ┆ borough  │
│ e          ┆ t_time_est ┆ time_est   ┆ inches     ┆ mins      ┆ nfluenced ┆ me        ┆ ---      │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str        ┆ datetime[μ ┆ datetime[μ ┆ f64        ┆ f64       ┆ str       ┆ str       ┆          │
│            ┆ s, America ┆ s, America ┆            ┆           ┆           ┆           ┆          │
│            ┆ /New_York] ┆ /New_York] ┆            ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 40.87      ┆ 664.96    ┆ Yes       ┆ Davenport ┆ Queens   │
│ Davenport  ┆ 05:24:23   ┆ 16:29:21   ┆            ┆           ┆           ┆ Court     ┆          │
│ Ct 1       ┆ EST        ┆ EST        ┆            ┆           ┆           ┆           ┆          │
│ Q - Beach  ┆ 2022-12-23 ┆ 2022-12-23 ┆ 38.19      ┆ 378.31    ┆ Yes       ┆ Beach     ┆ Queens   │
│ 84 St      ┆ 05:00:52   ┆ 11:19:11   ┆            ┆           ┆           ┆ 84th      ┆          │
│            ┆ EST        ┆ EST        ┆            ┆           ┆           ┆ Street    ┆          │
│ BK -       ┆ 2023-09-29 ┆ 2023-09-29 ┆ 35.94      ┆ 129.18    ┆ No        ┆ Carroll   ┆ Brooklyn │
│ Carroll    ┆ 07:53:39   ┆ 10:02:50   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/4th Av  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ BK -       ┆ 2021-09-01 ┆ 2021-09-01 ┆ 35.59      ┆ 104.17    ┆ No        ┆ Carroll   ┆ Brooklyn │
│ Carroll    ┆ 21:27:16   ┆ 23:11:26   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/4th Av  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Q -        ┆ 2024-01-13 ┆ 2024-01-13 ┆ 34.69      ┆ 553.46    ┆ Yes       ┆ Davenport ┆ Queens   │
│ Davenport  ┆ 08:05:35   ┆ 17:19:03   ┆            ┆           ┆           ┆ Court     ┆          │
│ Ct 1       ┆ EST        ┆ EST        ┆            ┆           ┆           ┆           ┆          │
│ BX -       ┆ 2024-04-03 ┆ 2024-04-04 ┆ 34.65      ┆ 870.27    ┆ Yes       ┆ Ditmars   ┆ Bronx    │
│ Ditmars    ┆ 12:04:19   ┆ 02:34:36   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/Hunter  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Ave 2      ┆            ┆            ┆            ┆           ┆           ┆           ┆          │
│ Q - Beach  ┆ 2024-01-13 ┆ 2024-01-13 ┆ 32.52      ┆ 348.63    ┆ Yes       ┆ Beach     ┆ Queens   │
│ 84 St      ┆ 06:59:39   ┆ 12:48:17   ┆            ┆           ┆           ┆ 84th      ┆          │
│            ┆ EST        ┆ EST        ┆            ┆           ┆           ┆ Street    ┆          │
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 31.77      ┆ 382.38    ┆ Yes       ┆ Russell   ┆ Queens   │
│ Russell St ┆ 05:12:13   ┆ 11:34:35   ┆            ┆           ┆           ┆ Street    ┆          │
│ 2          ┆ EST        ┆ EST        ┆            ┆           ┆           ┆           ┆          │
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 31.34      ┆ 353.47    ┆ Yes       ┆ Russell   ┆ Queens   │
│ Russell St ┆ 05:10:48   ┆ 11:04:16   ┆            ┆           ┆           ┆ Street    ┆          │
│ 1          ┆ EST        ┆ EST        ┆            ┆           ┆           ┆           ┆          │
│ BK -       ┆ 2022-09-13 ┆ 2022-09-13 ┆ 31.3       ┆ 46.28     ┆ No        ┆ Carroll   ┆ Brooklyn │
│ Carroll    ┆ 04:35:09   ┆ 05:21:25   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/4th Av  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
└────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴──────────┘

## 1.2 Top 10 Sensors by Maximum Flood Depth.
Table is ranked by depth per unique sensor. We take the greatest depth per sensor.

In [8]:
sql = """
    SELECT
        DISTINCT ON(sensor_name)
        sensor_name,
        flood_start_time_est,
        flood_end_time_est,
        max_depth_inches,
        duration_mins,
        tidally_influenced,
        street_name,
        borough
    FROM merged_df
    ORDER BY max_depth_inches DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬──────────┐
│ sensor_nam ┆ flood_star ┆ flood_end_ ┆ max_depth_ ┆ duration_ ┆ tidally_i ┆ street_na ┆ borough  │
│ e          ┆ t_time_est ┆ time_est   ┆ inches     ┆ mins      ┆ nfluenced ┆ me        ┆ ---      │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str        ┆ datetime[μ ┆ datetime[μ ┆ f64        ┆ f64       ┆ str       ┆ str       ┆          │
│            ┆ s, America ┆ s, America ┆            ┆           ┆           ┆           ┆          │
│            ┆ /New_York] ┆ /New_York] ┆            ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 40.87      ┆ 664.96    ┆ Yes       ┆ Davenport ┆ Queens   │
│ Davenport  ┆ 05:24:23   ┆ 16:29:21   ┆            ┆           ┆           ┆ Court     ┆          │
│ Ct 1       ┆ EST        ┆ EST        ┆            ┆           ┆           ┆           ┆          │
│ Q - Beach  ┆ 2022-12-23 ┆ 2022-12-23 ┆ 38.19      ┆ 378.31    ┆ Yes       ┆ Beach     ┆ Queens   │
│ 84 St      ┆ 05:00:52   ┆ 11:19:11   ┆            ┆           ┆           ┆ 84th      ┆          │
│            ┆ EST        ┆ EST        ┆            ┆           ┆           ┆ Street    ┆          │
│ BK -       ┆ 2023-09-29 ┆ 2023-09-29 ┆ 35.94      ┆ 129.18    ┆ No        ┆ Carroll   ┆ Brooklyn │
│ Carroll    ┆ 07:53:39   ┆ 10:02:50   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/4th Av  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ BX -       ┆ 2024-04-03 ┆ 2024-04-04 ┆ 34.65      ┆ 870.27    ┆ Yes       ┆ Ditmars   ┆ Bronx    │
│ Ditmars    ┆ 12:04:19   ┆ 02:34:36   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/Hunter  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Ave 2      ┆            ┆            ┆            ┆           ┆           ┆           ┆          │
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 31.77      ┆ 382.38    ┆ Yes       ┆ Russell   ┆ Queens   │
│ Russell St ┆ 05:12:13   ┆ 11:34:35   ┆            ┆           ┆           ┆ Street    ┆          │
│ 2          ┆ EST        ┆ EST        ┆            ┆           ┆           ┆           ┆          │
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 31.34      ┆ 353.47    ┆ Yes       ┆ Russell   ┆ Queens   │
│ Russell St ┆ 05:10:48   ┆ 11:04:16   ┆            ┆           ┆           ┆ Street    ┆          │
│ 1          ┆ EST        ┆ EST        ┆            ┆           ┆           ┆           ┆          │
│ BK - 9th   ┆ 2021-09-01 ┆ 2021-09-02 ┆ 27.76      ┆ 270.57    ┆ No        ┆ 9th       ┆ Brooklyn │
│ St/Smith   ┆ 20:11:58   ┆ 00:42:32   ┆            ┆           ┆           ┆ Street    ┆          │
│ St         ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ BK -       ┆ 2023-09-29 ┆ 2023-09-29 ┆ 25.08      ┆ 178.0     ┆ No        ┆ Wallabout ┆ Brooklyn │
│ Wallabout  ┆ 08:05:49   ┆ 11:03:49   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/Throop  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Ave        ┆            ┆            ┆            ┆           ┆           ┆           ┆          │
│ BK - Lee   ┆ 2023-09-29 ┆ 2023-09-29 ┆ 23.54      ┆ 245.39    ┆ No        ┆ Lee       ┆ Brooklyn │
│ Ave/Middle ┆ 08:07:18   ┆ 12:12:42   ┆            ┆           ┆           ┆ Avenue    ┆          │
│ ton St     ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Q - Beach  ┆ 2022-12-23 ┆ 2022-12-23 ┆ 23.43      ┆ 229.91    ┆ Yes       ┆ Beach     ┆ Queens   │
│ 43rd St    ┆ 06:07:36   ┆ 09:57:30   ┆            ┆           ┆           ┆ 43rd      ┆          │
│            ┆ EST        ┆ EST        ┆            ┆           ┆           ┆ Street    ┆          │
└────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴──────────┘

## 1.3 Top 10 Tidally Influenced Sensors by Maximum Flood Depth.

In [9]:
sql = """
    SELECT
        DISTINCT ON(sensor_name) 
        sensor_name,
        flood_start_time_est,
        flood_end_time_est,
        max_depth_inches,
        duration_mins,
        tidally_influenced,
        street_name,
        borough
    FROM merged_df
    WHERE tidally_influenced == 'Yes'
    ORDER BY max_depth_inches DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬─────────┐
│ sensor_nam ┆ flood_star ┆ flood_end_ ┆ max_depth_ ┆ duration_m ┆ tidally_i ┆ street_na ┆ borough │
│ e          ┆ t_time_est ┆ time_est   ┆ inches     ┆ ins        ┆ nfluenced ┆ me        ┆ ---     │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ str     │
│ str        ┆ datetime[μ ┆ datetime[μ ┆ f64        ┆ f64        ┆ str       ┆ str       ┆         │
│            ┆ s, America ┆ s, America ┆            ┆            ┆           ┆           ┆         │
│            ┆ /New_York] ┆ /New_York] ┆            ┆            ┆           ┆           ┆         │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═════════╡
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 40.87      ┆ 664.96     ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 05:24:23   ┆ 16:29:21   ┆            ┆            ┆           ┆ Court     ┆         │
│ Ct 1       ┆ EST        ┆ EST        ┆            ┆            ┆           ┆           ┆         │
│ Q - Beach  ┆ 2022-12-23 ┆ 2022-12-23 ┆ 38.19      ┆ 378.31     ┆ Yes       ┆ Beach     ┆ Queens  │
│ 84 St      ┆ 05:00:52   ┆ 11:19:11   ┆            ┆            ┆           ┆ 84th      ┆         │
│            ┆ EST        ┆ EST        ┆            ┆            ┆           ┆ Street    ┆         │
│ BX -       ┆ 2024-04-03 ┆ 2024-04-04 ┆ 34.65      ┆ 870.27     ┆ Yes       ┆ Ditmars   ┆ Bronx   │
│ Ditmars    ┆ 12:04:19   ┆ 02:34:36   ┆            ┆            ┆           ┆ Street    ┆         │
│ St/Hunter  ┆ EDT        ┆ EDT        ┆            ┆            ┆           ┆           ┆         │
│ Ave 2      ┆            ┆            ┆            ┆            ┆           ┆           ┆         │
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 31.77      ┆ 382.38     ┆ Yes       ┆ Russell   ┆ Queens  │
│ Russell St ┆ 05:12:13   ┆ 11:34:35   ┆            ┆            ┆           ┆ Street    ┆         │
│ 2          ┆ EST        ┆ EST        ┆            ┆            ┆           ┆           ┆         │
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 31.34      ┆ 353.47     ┆ Yes       ┆ Russell   ┆ Queens  │
│ Russell St ┆ 05:10:48   ┆ 11:04:16   ┆            ┆            ┆           ┆ Street    ┆         │
│ 1          ┆ EST        ┆ EST        ┆            ┆            ┆           ┆           ┆         │
│ Q - Beach  ┆ 2022-12-23 ┆ 2022-12-23 ┆ 23.43      ┆ 229.91     ┆ Yes       ┆ Beach     ┆ Queens  │
│ 43rd St    ┆ 06:07:36   ┆ 09:57:30   ┆            ┆            ┆           ┆ 43rd      ┆         │
│            ┆ EST        ┆ EST        ┆            ┆            ┆           ┆ Street    ┆         │
│ Q - 102nd  ┆ 2024-01-13 ┆ 2024-01-13 ┆ 21.69      ┆ 271.78     ┆ Yes       ┆ 102nd     ┆ Queens  │
│ St/160th   ┆ 07:46:45   ┆ 12:18:31   ┆            ┆            ┆           ┆ Street    ┆         │
│ Ave        ┆ EST        ┆ EST        ┆            ┆            ┆           ┆           ┆         │
│ Q - Beach  ┆ 2024-01-13 ┆ 2024-01-13 ┆ 21.5       ┆ 457.29     ┆ Yes       ┆ Beach     ┆ Queens  │
│ 72nd       ┆ 09:15:14   ┆ 16:52:32   ┆            ┆            ┆           ┆ 72nd      ┆         │
│ St/Almeda  ┆ EST        ┆ EST        ┆            ┆            ┆           ┆ Street    ┆         │
│ Ave        ┆            ┆            ┆            ┆            ┆           ┆           ┆         │
│ Q - Beach  ┆ 2025-10-30 ┆ 2025-10-30 ┆ 20.43      ┆ 290.98     ┆ Yes       ┆ Beach     ┆ Queens  │
│ 84 St (2)  ┆ 13:42:55   ┆ 18:33:54   ┆            ┆            ┆           ┆ 84th      ┆         │
│            ┆ EDT        ┆ EDT        ┆            ┆            ┆           ┆ Street    ┆         │
│ Q - 161st  ┆ 2024-01-13 ┆ 2024-01-13 ┆ 20.08      ┆ 255.9      ┆ Yes       ┆ 161st     ┆ Queens  │
│ Ave/99th   ┆ 08:16:44   ┆ 12:32:37   ┆            ┆            ┆           ┆ Avenue,   ┆         │
│ St         ┆ EST        ┆ EST        ┆            ┆            ┆           ┆ Grimm     ┆         │
│            ┆            ┆            ┆            ┆            ┆           ┆ Avenue    ┆         │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴─────────┘

## 1.4 Top 10 Non-Tidally Influenced Sensors by Maximum Flood Depth.
Non-tidally influenced sensors are sometimes evaluated independently, since their flood depths are driven primarily by rainfall and drainage conditions rather than tidal cycles, resulting in different flooding dynamics than tidally influenced sensors. This is visible if the frequency of flooding events.

In [10]:
sql = """
    SELECT
        DISTINCT ON(sensor_name) 
        sensor_name,
        flood_start_time_est,
        flood_end_time_est,
        max_depth_inches,
        duration_mins,
        tidally_influenced,
        street_name,
        borough
    FROM merged_df
    WHERE tidally_influenced == 'No'
    ORDER BY max_depth_inches DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬──────────┐
│ sensor_nam ┆ flood_star ┆ flood_end_ ┆ max_depth_ ┆ duration_ ┆ tidally_i ┆ street_na ┆ borough  │
│ e          ┆ t_time_est ┆ time_est   ┆ inches     ┆ mins      ┆ nfluenced ┆ me        ┆ ---      │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str        ┆ datetime[μ ┆ datetime[μ ┆ f64        ┆ f64       ┆ str       ┆ str       ┆          │
│            ┆ s, America ┆ s, America ┆            ┆           ┆           ┆           ┆          │
│            ┆ /New_York] ┆ /New_York] ┆            ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ BK -       ┆ 2023-09-29 ┆ 2023-09-29 ┆ 35.94      ┆ 129.18    ┆ No        ┆ Carroll   ┆ Brooklyn │
│ Carroll    ┆ 07:53:39   ┆ 10:02:50   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/4th Av  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ BK - 9th   ┆ 2021-09-01 ┆ 2021-09-02 ┆ 27.76      ┆ 270.57    ┆ No        ┆ 9th       ┆ Brooklyn │
│ St/Smith   ┆ 20:11:58   ┆ 00:42:32   ┆            ┆           ┆           ┆ Street    ┆          │
│ St         ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ BK -       ┆ 2023-09-29 ┆ 2023-09-29 ┆ 25.08      ┆ 178.0     ┆ No        ┆ Wallabout ┆ Brooklyn │
│ Wallabout  ┆ 08:05:49   ┆ 11:03:49   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/Throop  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Ave        ┆            ┆            ┆            ┆           ┆           ┆           ┆          │
│ BK - Lee   ┆ 2023-09-29 ┆ 2023-09-29 ┆ 23.54      ┆ 245.39    ┆ No        ┆ Lee       ┆ Brooklyn │
│ Ave/Middle ┆ 08:07:18   ┆ 12:12:42   ┆            ┆           ┆           ┆ Avenue    ┆          │
│ ton St     ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ BK -       ┆ 2025-10-30 ┆ 2025-10-30 ┆ 23.35      ┆ 144.24    ┆ No        ┆ Kingston  ┆ Brooklyn │
│ Kingston   ┆ 15:02:07   ┆ 17:26:22   ┆            ┆           ┆           ┆ Avenue    ┆          │
│ Ave/Rutlan ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ d Rd       ┆            ┆            ┆            ┆           ┆           ┆           ┆          │
│ Q - 204th  ┆ 2025-10-30 ┆ 2025-10-30 ┆ 23.35      ┆ 43.02     ┆ No        ┆ 204th     ┆ Queens   │
│ St/ 100th  ┆ 16:04:44   ┆ 16:47:45   ┆            ┆           ┆           ┆ Street    ┆          │
│ Ave        ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ BK - Knick ┆ 2025-10-30 ┆ 2025-10-30 ┆ 22.76      ┆ 126.48    ┆ No        ┆ Knickerbo ┆ Brooklyn │
│ erbocker   ┆ 15:09:13   ┆ 17:15:42   ┆            ┆           ┆           ┆ cker      ┆          │
│ Ave/ Hart  ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆ Avenue    ┆          │
│ S…         ┆            ┆            ┆            ┆           ┆           ┆           ┆          │
│ Q - Peck   ┆ 2025-10-30 ┆ 2025-10-30 ┆ 22.64      ┆ 106.0     ┆ No        ┆ 153rd     ┆ Queens   │
│ Ave/153rd  ┆ 15:54:42   ┆ 17:40:42   ┆            ┆           ┆           ┆ Street    ┆          │
│ st         ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Q - 56th   ┆ 2025-10-30 ┆ 2025-10-30 ┆ 21.93      ┆ 218.98    ┆ No        ┆ 56th      ┆ Queens   │
│ Ave/ Sprin ┆ 15:51:23   ┆ 19:30:22   ┆            ┆           ┆           ┆ Avenue    ┆          │
│ gfield     ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Blvd       ┆            ┆            ┆            ┆           ┆           ┆           ┆          │
│ BK -       ┆ 2023-09-29 ┆ 2023-09-29 ┆ 21.61      ┆ 231.88    ┆ No        ┆ Walton    ┆ Brooklyn │
│ Walton     ┆ 08:08:57   ┆ 12:00:50   ┆            ┆           ┆           ┆ Street    ┆          │
│ St/Marcy   ┆ EDT        ┆ EDT        ┆            ┆           ┆           ┆           ┆          │
│ Ave        ┆            ┆            ┆            ┆           ┆           ┆           ┆          │
└────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴──────────┘

# 2) Frequency of Flood Events
Counts are normalized by the number of days each sensor was deployed. As sensors were installed in different years, raw event counts are not directly comparable without normalization.

## Normalize Event Counts

In [11]:
deployment_days = duckdb.sql("""
    SELECT
        sensor_id,
        date_diff('day', date_installed, current_date()) AS deployment_days
    FROM metadata_df
""")

flood_events = duckdb.sql("""
    SELECT
        sensor_id,
        sensor_name,
        street_name,
        borough,
        tidally_influenced,
        COUNT(*) AS flood_events,
    FROM merged_df
    GROUP BY ALL
""")

sql = """
    SELECT
        *,
        ROUND(flood_events /  deployment_days * (365 / 12.), 2) AS flood_events_per_month
    FROM flood_events
    JOIN deployment_days USING (sensor_id)
    ORDER BY flood_events_per_month DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬─────────┬────────────┬────────────┬───────────┬───────────┐
│ sensor_id  ┆ sensor_nam ┆ street_nam ┆ borough ┆ tidally_in ┆ flood_even ┆ deploymen ┆ flood_eve │
│ ---        ┆ e          ┆ e          ┆ ---     ┆ fluenced   ┆ ts         ┆ t_days    ┆ nts_per_m │
│ str        ┆ ---        ┆ ---        ┆ str     ┆ ---        ┆ ---        ┆ ---       ┆ onth      │
│            ┆ str        ┆ str        ┆         ┆ str        ┆ i64        ┆ i64       ┆ ---       │
│            ┆            ┆            ┆         ┆            ┆            ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═════════╪════════════╪════════════╪═══════════╪═══════════╡
│ BX-ditmars ┆ BX -       ┆ Ditmars    ┆ Bronx   ┆ Yes        ┆ 288        ┆ 879       ┆ 9.97      │
│ -st-hunter ┆ Ditmars    ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ -ave-1kwrk ┆ St/Hunter  ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Ave 2      ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-beach-84 ┆ Q - Beach  ┆ Beach 84th ┆ Queens  ┆ Yes        ┆ 376        ┆ 1550      ┆ 7.38      │
│ -st-0me680 ┆ 84 St      ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens  ┆ Yes        ┆ 79         ┆ 515       ┆ 4.67      │
│ le-blvd-ro ┆ Brookville ┆ Boulevard  ┆         ┆            ┆            ┆           ┆           │
│ ckaway-blv ┆ Blvd/      ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-beach-84 ┆ Q - Beach  ┆ Beach 84th ┆ Queens  ┆ Yes        ┆ 16         ┆ 131       ┆ 3.72      │
│ th-st-beac ┆ 84 St (2)  ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ h-channel- ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens  ┆ Yes        ┆ 52         ┆ 515       ┆ 3.07      │
│ le-blvd-ro ┆ Brookville ┆ Boulevard  ┆         ┆            ┆            ┆           ┆           │
│ ckaway-blv ┆ Blvd/      ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens  ┆ Yes        ┆ 42         ┆ 515       ┆ 2.48      │
│ le-blvd-14 ┆ Brookville ┆ Boulevard  ┆         ┆            ┆            ┆           ┆           │
│ 9th-ave-3- ┆ Blvd/      ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-beach-35 ┆ Q - Beach  ┆ Beach 35th ┆ Queens  ┆ Yes        ┆ 58         ┆ 811       ┆ 2.18      │
│ -st-beach- ┆ 35         ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ channel-dr ┆ St/Beach   ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Channel …  ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-russell- ┆ Q -        ┆ Russell    ┆ Queens  ┆ Yes        ┆ 125        ┆ 1830      ┆ 2.08      │
│ st-1-07zqc ┆ Russell St ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ 0          ┆ 1          ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-102nd-st ┆ Q - 102nd  ┆ 102nd      ┆ Queens  ┆ Yes        ┆ 71         ┆ 1088      ┆ 1.98      │
│ -160th-ave ┆ St/160th   ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ -1a5ng0    ┆ Ave        ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-161st-av ┆ Q - 161st  ┆ 161st      ┆ Queens  ┆ Yes        ┆ 58         ┆ 1088      ┆ 1.62      │
│ e-99th-st- ┆ Ave/99th   ┆ Avenue,    ┆         ┆            ┆            ┆           ┆           │
│ 1a5q80     ┆ St         ┆ Grimm      ┆         ┆            ┆            ┆           ┆           │
│            ┆            ┆ Avenue     ┆         ┆            ┆            ┆           ┆           │
└────────────┴────────────┴────────────┴─────────┴────────────┴────────────┴───────────┴───────────┘

## 2.1 Top 10 Highest Number of Events by Tidally Influenced Sensors.

In [12]:
sql = """
    SELECT
        *,
        ROUND(flood_events / deployment_days * (365 / 12.), 2) AS flood_events_per_month
    FROM flood_events
    JOIN deployment_days USING (sensor_id)
    WHERE tidally_influenced == 'Yes'
    ORDER BY flood_events_per_month DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬─────────┬────────────┬────────────┬───────────┬───────────┐
│ sensor_id  ┆ sensor_nam ┆ street_nam ┆ borough ┆ tidally_in ┆ flood_even ┆ deploymen ┆ flood_eve │
│ ---        ┆ e          ┆ e          ┆ ---     ┆ fluenced   ┆ ts         ┆ t_days    ┆ nts_per_m │
│ str        ┆ ---        ┆ ---        ┆ str     ┆ ---        ┆ ---        ┆ ---       ┆ onth      │
│            ┆ str        ┆ str        ┆         ┆ str        ┆ i64        ┆ i64       ┆ ---       │
│            ┆            ┆            ┆         ┆            ┆            ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═════════╪════════════╪════════════╪═══════════╪═══════════╡
│ BX-ditmars ┆ BX -       ┆ Ditmars    ┆ Bronx   ┆ Yes        ┆ 288        ┆ 879       ┆ 9.97      │
│ -st-hunter ┆ Ditmars    ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ -ave-1kwrk ┆ St/Hunter  ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Ave 2      ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-beach-84 ┆ Q - Beach  ┆ Beach 84th ┆ Queens  ┆ Yes        ┆ 376        ┆ 1550      ┆ 7.38      │
│ -st-0me680 ┆ 84 St      ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens  ┆ Yes        ┆ 79         ┆ 515       ┆ 4.67      │
│ le-blvd-ro ┆ Brookville ┆ Boulevard  ┆         ┆            ┆            ┆           ┆           │
│ ckaway-blv ┆ Blvd/      ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-beach-84 ┆ Q - Beach  ┆ Beach 84th ┆ Queens  ┆ Yes        ┆ 16         ┆ 131       ┆ 3.72      │
│ th-st-beac ┆ 84 St (2)  ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ h-channel- ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens  ┆ Yes        ┆ 52         ┆ 515       ┆ 3.07      │
│ le-blvd-ro ┆ Brookville ┆ Boulevard  ┆         ┆            ┆            ┆           ┆           │
│ ckaway-blv ┆ Blvd/      ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens  ┆ Yes        ┆ 42         ┆ 515       ┆ 2.48      │
│ le-blvd-14 ┆ Brookville ┆ Boulevard  ┆         ┆            ┆            ┆           ┆           │
│ 9th-ave-3- ┆ Blvd/      ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-beach-35 ┆ Q - Beach  ┆ Beach 35th ┆ Queens  ┆ Yes        ┆ 58         ┆ 811       ┆ 2.18      │
│ -st-beach- ┆ 35         ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ channel-dr ┆ St/Beach   ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ Channel …  ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-russell- ┆ Q -        ┆ Russell    ┆ Queens  ┆ Yes        ┆ 125        ┆ 1830      ┆ 2.08      │
│ st-1-07zqc ┆ Russell St ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ 0          ┆ 1          ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-102nd-st ┆ Q - 102nd  ┆ 102nd      ┆ Queens  ┆ Yes        ┆ 71         ┆ 1088      ┆ 1.98      │
│ -160th-ave ┆ St/160th   ┆ Street     ┆         ┆            ┆            ┆           ┆           │
│ -1a5ng0    ┆ Ave        ┆            ┆         ┆            ┆            ┆           ┆           │
│ Q-161st-av ┆ Q - 161st  ┆ 161st      ┆ Queens  ┆ Yes        ┆ 58         ┆ 1088      ┆ 1.62      │
│ e-99th-st- ┆ Ave/99th   ┆ Avenue,    ┆         ┆            ┆            ┆           ┆           │
│ 1a5q80     ┆ St         ┆ Grimm      ┆         ┆            ┆            ┆           ┆           │
│            ┆            ┆ Avenue     ┆         ┆            ┆            ┆           ┆           │
└────────────┴────────────┴────────────┴─────────┴────────────┴────────────┴───────────┴───────────┘

## 2.2 Highest Number of Events by Non-Tidally Influenced Sensors.

In [13]:
sql = """
    SELECT
        *,
        ROUND(flood_events / deployment_days * (365 / 12.), 2) AS flood_events_per_month
    FROM flood_events
    JOIN deployment_days USING (sensor_id)
    WHERE tidally_influenced = 'No'
    ORDER BY flood_events_per_month DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ sensor_id  ┆ sensor_nam ┆ street_nam ┆ borough   ┆ tidally_i ┆ flood_eve ┆ deploymen ┆ flood_eve │
│ ---        ┆ e          ┆ e          ┆ ---       ┆ nfluenced ┆ nts       ┆ t_days    ┆ nts_per_m │
│ str        ┆ ---        ┆ ---        ┆ str       ┆ ---       ┆ ---       ┆ ---       ┆ onth      │
│            ┆ str        ┆ str        ┆           ┆ str       ┆ i64       ┆ i64       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ BX-w-234th ┆ BX -       ┆ Tibbett    ┆ Bronx     ┆ No        ┆ 11        ┆ 347       ┆ 0.96      │
│ -st-tibbet ┆ Tibbett    ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ t-ave-2cak ┆ Ave/W      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ 234th St   ┆            ┆           ┆           ┆           ┆           ┆           │
│ BX-webster ┆ BX -       ┆ Webster    ┆ Bronx     ┆ No        ┆ 15        ┆ 564       ┆ 0.81      │
│ -ave-e-166 ┆ Webster    ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ th-st-2151 ┆ Ave/E      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ 166th St   ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-neptune ┆ BK -       ┆ West 35th  ┆ Brooklyn  ┆ No        ┆ 12        ┆ 627       ┆ 0.58      │
│ -ave-w-35t ┆ Neptune    ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ h-st-1xvfk ┆ Ave W 35th ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ St         ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-wythe-a ┆ BK - Wythe ┆ Wythe      ┆ Brooklyn  ┆ No        ┆ 19        ┆ 1096      ┆ 0.53      │
│ ve-wallabo ┆ Ave/Wallab ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ ut-st-19qz ┆ out St     ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-56th-ave ┆ Q - 56th   ┆ 56th       ┆ Queens    ┆ No        ┆ 3         ┆ 179       ┆ 0.51      │
│ -springfie ┆ Ave/ Sprin ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ ld-blvd-1z ┆ gfield     ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Blvd       ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-fountai ┆ BK -       ┆ Flatlands  ┆ Brooklyn  ┆ No        ┆ 8         ┆ 563       ┆ 0.43      │
│ n-ave-flat ┆ Fountain   ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ lands-ave- ┆ Ave/Flatla ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ nds Av…    ┆            ┆           ┆           ┆           ┆           ┆           │
│ SI-haven-a ┆ SI - Haven ┆ Adams      ┆ Staten    ┆ No        ┆ 11        ┆ 770       ┆ 0.43      │
│ ve-adam-av ┆ Ave/ Adam  ┆ Avenue     ┆ Island    ┆           ┆           ┆           ┆           │
│ e-1qijg0   ┆ Ave        ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-hoyt-st ┆ BK - Hoyt  ┆ Hoyt       ┆ Brooklyn  ┆ No        ┆ 25        ┆ 1981      ┆ 0.38      │
│ -5th-st-00 ┆ St/5th St  ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ 7sk0       ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-2nd-ave ┆ BK - 2nd   ┆ 2nd Avenue ┆ Brooklyn  ┆ No        ┆ 2         ┆ 173       ┆ 0.35      │
│ -49th-st-2 ┆ Ave/49th   ┆            ┆           ┆           ┆           ┆           ┆           │
│ l8qvc      ┆ St         ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-caton-a ┆ BK - Caton ┆ Caton      ┆ Brooklyn  ┆ No        ┆ 2         ┆ 172       ┆ 0.35      │
│ ve-e-8th-s ┆ Ave/E      ┆ Avenue,    ┆           ┆           ┆           ┆           ┆           │
│ t-2lavl0   ┆ Eighth St  ┆ State      ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ Route 27   ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

# 3) Flood Duration
Examine highest total flood duration of any event.

## 3.1 Top 10 Tidally Influenced Sensors by Longest Flood Duration.

In [14]:
sql = """
    SELECT
        sensor_name,
        flood_start_time_est,
        flood_end_time_est,
        duration_mins,
        max_depth_inches,
        tidally_influenced,
        street_name,
        borough
    FROM merged_df
    WHERE tidally_influenced = 'Yes'
    ORDER BY duration_mins DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ sensor_nam ┆ flood_star ┆ flood_end_ ┆ duration_ ┆ max_depth ┆ tidally_i ┆ street_na ┆ borough   │
│ e          ┆ t_time_est ┆ time_est   ┆ mins      ┆ _inches   ┆ nfluenced ┆ me        ┆ ---       │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│ str        ┆ datetime[μ ┆ datetime[μ ┆ f64       ┆ f64       ┆ str       ┆ str       ┆           │
│            ┆ s, America ┆ s, America ┆           ┆           ┆           ┆           ┆           │
│            ┆ /New_York] ┆ /New_York] ┆           ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SI -       ┆ 2025-02-16 ┆ 2025-02-18 ┆ 3485.99   ┆ 3.31      ┆ Yes       ┆ Quincy    ┆ Staten    │
│ Quincy     ┆ 01:31:03   ┆ 11:37:03   ┆           ┆           ┆           ┆ Avenue,   ┆ Island    │
│ Ave/Iona   ┆ EST        ┆ EST        ┆           ┆           ┆           ┆ Comanche  ┆           │
│ St         ┆            ┆            ┆           ┆           ┆           ┆ Avenue    ┆           │
│ SI -       ┆ 2024-04-02 ┆ 2024-04-04 ┆ 2886.13   ┆ 3.98      ┆ Yes       ┆ Quincy    ┆ Staten    │
│ Quincy     ┆ 14:36:42   ┆ 14:42:50   ┆           ┆           ┆           ┆ Avenue,   ┆ Island    │
│ Ave/Iona   ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆ Comanche  ┆           │
│ St         ┆            ┆            ┆           ┆           ┆           ┆ Avenue    ┆           │
│ BX - Cross ┆ 2024-04-02 ┆ 2024-04-04 ┆ 2698.82   ┆ 2.52      ┆ Yes       ┆ Minniefor ┆ Bronx     │
│ St/Minnief ┆ 15:17:22   ┆ 12:16:11   ┆           ┆           ┆           ┆ d Avenue  ┆           │
│ ord Ave    ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆           ┆           │
│ SI -       ┆ 2023-10-20 ┆ 2023-10-22 ┆ 2627.65   ┆ 3.46      ┆ Yes       ┆ Quincy    ┆ Staten    │
│ Quincy     ┆ 16:22:29   ┆ 12:10:08   ┆           ┆           ┆           ┆ Avenue,   ┆ Island    │
│ Ave/Iona   ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆ Comanche  ┆           │
│ St         ┆            ┆            ┆           ┆           ┆           ┆ Avenue    ┆           │
│ SI -       ┆ 2023-09-29 ┆ 2023-09-30 ┆ 2166.14   ┆ 5.59      ┆ Yes       ┆ Quincy    ┆ Staten    │
│ Quincy     ┆ 03:53:34   ┆ 15:59:42   ┆           ┆           ┆           ┆ Avenue,   ┆ Island    │
│ Ave/Iona   ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆ Comanche  ┆           │
│ St         ┆            ┆            ┆           ┆           ┆           ┆ Avenue    ┆           │
│ SI -       ┆ 2025-05-22 ┆ 2025-05-23 ┆ 1946.75   ┆ 1.97      ┆ Yes       ┆ Quincy    ┆ Staten    │
│ Quincy     ┆ 05:44:09   ┆ 14:10:54   ┆           ┆           ┆           ┆ Avenue,   ┆ Island    │
│ Ave/Iona   ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆ Comanche  ┆           │
│ St         ┆            ┆            ┆           ┆           ┆           ┆ Avenue    ┆           │
│ Q -        ┆ 2022-10-03 ┆ 2022-10-04 ┆ 1828.59   ┆ 7.48      ┆ Yes       ┆ Russell   ┆ Queens    │
│ Russell St ┆ 13:48:55   ┆ 20:17:31   ┆           ┆           ┆           ┆ Street    ┆           │
│ 2          ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆           ┆           │
│ BX - Cross ┆ 2024-03-06 ┆ 2024-03-07 ┆ 1702.46   ┆ 2.05      ┆ Yes       ┆ Minniefor ┆ Bronx     │
│ St/Minnief ┆ 15:56:28   ┆ 20:18:55   ┆           ┆           ┆           ┆ d Avenue  ┆           │
│ ord Ave    ┆ EST        ┆ EST        ┆           ┆           ┆           ┆           ┆           │
│ BX - Cross ┆ 2024-01-28 ┆ 2024-01-29 ┆ 1621.88   ┆ 1.5       ┆ Yes       ┆ Minniefor ┆ Bronx     │
│ St/Minnief ┆ 06:35:01   ┆ 09:36:54   ┆           ┆           ┆           ┆ d Avenue  ┆           │
│ ord Ave    ┆ EST        ┆ EST        ┆           ┆           ┆           ┆           ┆           │
│ SI -       ┆ 2025-05-14 ┆ 2025-05-15 ┆ 1560.2    ┆ 2.76      ┆ Yes       ┆ Quincy    ┆ Staten    │
│ Quincy     ┆ 08:48:12   ┆ 10:48:24   ┆           ┆           ┆           ┆ Avenue,   ┆ Island    │
│ Ave/Iona   ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆ Comanche  ┆           │
│ St         ┆            ┆            ┆           ┆           ┆           ┆ Avenue    ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## 3.2 Top 10 Non-Tidally Influenced Sensors by Longest Flood Duration.

In [15]:
sql = """
    SELECT
        sensor_name,
        flood_start_time_est,
        flood_end_time_est,
        duration_mins,
        max_depth_inches,
        tidally_influenced,
        street_name,
        borough
    FROM merged_df
    WHERE tidally_influenced = 'No'
    ORDER BY duration_mins DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ sensor_nam ┆ flood_star ┆ flood_end_ ┆ duration_ ┆ max_depth ┆ tidally_i ┆ street_na ┆ borough   │
│ e          ┆ t_time_est ┆ time_est   ┆ mins      ┆ _inches   ┆ nfluenced ┆ me        ┆ ---       │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│ str        ┆ datetime[μ ┆ datetime[μ ┆ f64       ┆ f64       ┆ str       ┆ str       ┆           │
│            ┆ s, America ┆ s, America ┆           ┆           ┆           ┆           ┆           │
│            ┆ /New_York] ┆ /New_York] ┆           ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ BK - Hoyt  ┆ 2024-03-06 ┆ 2024-03-07 ┆ 1107.36   ┆ 4.25      ┆ No        ┆ Hoyt      ┆ Brooklyn  │
│ St/5th St  ┆ 16:10:53   ┆ 10:38:14   ┆           ┆           ┆           ┆ Street    ┆           │
│            ┆ EST        ┆ EST        ┆           ┆           ┆           ┆           ┆           │
│ BK - Hoyt  ┆ 2024-08-06 ┆ 2024-08-07 ┆ 1065.93   ┆ 4.17      ┆ No        ┆ Hoyt      ┆ Brooklyn  │
│ St/5th St  ┆ 18:45:32   ┆ 12:31:28   ┆           ┆           ┆           ┆ Street    ┆           │
│            ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆           ┆           │
│ BK - Hoyt  ┆ 2023-12-18 ┆ 2023-12-18 ┆ 1025.38   ┆ 5.59      ┆ No        ┆ Hoyt      ┆ Brooklyn  │
│ St/5th St  ┆ 01:08:45   ┆ 18:14:08   ┆           ┆           ┆           ┆ Street    ┆           │
│            ┆ EST        ┆ EST        ┆           ┆           ┆           ┆           ┆           │
│ BX - 1st   ┆ 2025-04-26 ┆ 2025-04-27 ┆ 758.24    ┆ 6.18      ┆ No        ┆ Avenue A  ┆ Bronx     │
│ St/Avenue  ┆ 19:17:20   ┆ 07:55:34   ┆           ┆           ┆           ┆           ┆           │
│ A          ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆           ┆           │
│ BX - 1st   ┆ 2025-03-05 ┆ 2025-03-06 ┆ 734.74    ┆ 4.29      ┆ No        ┆ Avenue A  ┆ Bronx     │
│ St/Avenue  ┆ 18:41:55   ┆ 06:56:39   ┆           ┆           ┆           ┆           ┆           │
│ A          ┆ EST        ┆ EST        ┆           ┆           ┆           ┆           ┆           │
│ BX -       ┆ 2025-12-02 ┆ 2025-12-02 ┆ 659.97    ┆ 1.14      ┆ No        ┆ Tibbett   ┆ Bronx     │
│ Tibbett    ┆ 10:00:42   ┆ 21:00:40   ┆           ┆           ┆           ┆ Avenue    ┆           │
│ Ave/W      ┆ EST        ┆ EST        ┆           ┆           ┆           ┆           ┆           │
│ 234th St   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ BX -       ┆ 2025-06-28 ┆ 2025-06-29 ┆ 628.97    ┆ 3.43      ┆ No        ┆ Webster   ┆ Bronx     │
│ Webster    ┆ 21:07:15   ┆ 07:36:13   ┆           ┆           ┆           ┆ Avenue    ┆           │
│ Ave/E      ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆           ┆           │
│ 166th St   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ SI - Haven ┆ 2024-03-23 ┆ 2024-03-23 ┆ 562.58    ┆ 5.28      ┆ No        ┆ Adams     ┆ Staten    │
│ Ave/ Adam  ┆ 12:32:44   ┆ 21:55:19   ┆           ┆           ┆           ┆ Avenue    ┆ Island    │
│ Ave        ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆           ┆           │
│ BX -       ┆ 2025-05-31 ┆ 2025-05-31 ┆ 560.61    ┆ 1.38      ┆ No        ┆ Tibbett   ┆ Bronx     │
│ Tibbett    ┆ 01:52:23   ┆ 11:13:00   ┆           ┆           ┆           ┆ Avenue    ┆           │
│ Ave/W      ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆           ┆           │
│ 234th St   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK -       ┆ 2025-09-28 ┆ 2025-09-28 ┆ 530.98    ┆ 3.11      ┆ No        ┆ Church    ┆ Brooklyn  │
│ Church     ┆ 03:13:28   ┆ 12:04:27   ┆           ┆           ┆           ┆ Avenue    ┆           │
│ Ave/E 53rd ┆ EDT        ┆ EDT        ┆           ┆           ┆           ┆           ┆           │
│ St         ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## 3.3 Top 10 Sensors by Flood Duration for Events Exceeding 12 inches.
We restrict the rankings to only large flooding events (i.e. 12 inches).

In [16]:
sql = """
    SELECT
        sensor_name,
        flood_start_time_est,
        flood_end_time_est,
        duration_mins,
        max_depth_inches,
        tidally_influenced,
        street_name,
        borough
    FROM merged_df
    WHERE tidally_influenced = 'Yes'
        AND max_depth_inches >= 12
    ORDER BY duration_mins DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬─────────┐
│ sensor_nam ┆ flood_star ┆ flood_end_ ┆ duration_m ┆ max_depth_ ┆ tidally_i ┆ street_na ┆ borough │
│ e          ┆ t_time_est ┆ time_est   ┆ ins        ┆ inches     ┆ nfluenced ┆ me        ┆ ---     │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ str     │
│ str        ┆ datetime[μ ┆ datetime[μ ┆ f64        ┆ f64        ┆ str       ┆ str       ┆         │
│            ┆ s, America ┆ s, America ┆            ┆            ┆           ┆           ┆         │
│            ┆ /New_York] ┆ /New_York] ┆            ┆            ┆           ┆           ┆         │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═════════╡
│ Q - Beach  ┆ 2022-01-01 ┆ 2022-01-02 ┆ 1012.26    ┆ 22.44      ┆ Yes       ┆ Beach     ┆ Queens  │
│ 84 St      ┆ 18:14:07   ┆ 11:06:22   ┆            ┆            ┆           ┆ 84th      ┆         │
│            ┆ EST        ┆ EST        ┆            ┆            ┆           ┆ Street    ┆         │
│ Q - Beach  ┆ 2023-09-29 ┆ 2023-09-29 ┆ 980.84     ┆ 16.65      ┆ Yes       ┆ Beach     ┆ Queens  │
│ 84 St      ┆ 06:51:28   ┆ 23:12:18   ┆            ┆            ┆           ┆ 84th      ┆         │
│            ┆ EDT        ┆ EDT        ┆            ┆            ┆           ┆ Street    ┆         │
│ BX -       ┆ 2024-04-03 ┆ 2024-04-04 ┆ 870.27     ┆ 34.65      ┆ Yes       ┆ Ditmars   ┆ Bronx   │
│ Ditmars    ┆ 12:04:19   ┆ 02:34:36   ┆            ┆            ┆           ┆ Street    ┆         │
│ St/Hunter  ┆ EDT        ┆ EDT        ┆            ┆            ┆           ┆           ┆         │
│ Ave 2      ┆            ┆            ┆            ┆            ┆           ┆           ┆         │
│ Q -        ┆ 2022-12-23 ┆ 2022-12-23 ┆ 664.96     ┆ 40.87      ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 05:24:23   ┆ 16:29:21   ┆            ┆            ┆           ┆ Court     ┆         │
│ Ct 1       ┆ EST        ┆ EST        ┆            ┆            ┆           ┆           ┆         │
│ Q -        ┆ 2023-09-29 ┆ 2023-09-29 ┆ 635.44     ┆ 15.43      ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 07:11:07   ┆ 17:46:33   ┆            ┆            ┆           ┆ Court     ┆         │
│ Ct 1       ┆ EDT        ┆ EDT        ┆            ┆            ┆           ┆           ┆         │
│ BX -       ┆ 2024-08-06 ┆ 2024-08-07 ┆ 582.53     ┆ 15.75      ┆ Yes       ┆ Ditmars   ┆ Bronx   │
│ Ditmars    ┆ 17:13:03   ┆ 02:55:34   ┆            ┆            ┆           ┆ Street    ┆         │
│ St/Hunter  ┆ EDT        ┆ EDT        ┆            ┆            ┆           ┆           ┆         │
│ Ave 2      ┆            ┆            ┆            ┆            ┆           ┆           ┆         │
│ Q -        ┆ 2024-01-13 ┆ 2024-01-13 ┆ 553.46     ┆ 34.69      ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 08:05:35   ┆ 17:19:03   ┆            ┆            ┆           ┆ Court     ┆         │
│ Ct 1       ┆ EST        ┆ EST        ┆            ┆            ┆           ┆           ┆         │
│ Q -        ┆ 2024-03-09 ┆ 2024-03-10 ┆ 548.48     ┆ 20.71      ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 18:52:22   ┆ 05:00:51   ┆            ┆            ┆           ┆ Court     ┆         │
│ Ct 1       ┆ EST        ┆ EDT        ┆            ┆            ┆           ┆           ┆         │
│ Q - Beach  ┆ 2023-09-29 ┆ 2023-09-29 ┆ 544.65     ┆ 12.24      ┆ Yes       ┆ Beach     ┆ Queens  │
│ 72nd       ┆ 10:30:26   ┆ 19:35:04   ┆            ┆            ┆           ┆ 72nd      ┆         │
│ St/Almeda  ┆ EDT        ┆ EDT        ┆            ┆            ┆           ┆ Street    ┆         │
│ Ave        ┆            ┆            ┆            ┆            ┆           ┆           ┆         │
│ Q -        ┆ 2024-04-04 ┆ 2024-04-04 ┆ 537.7      ┆ 20.83      ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 02:53:17   ┆ 11:50:59   ┆            ┆            ┆           ┆ Court     ┆         │
│ Ct 1       ┆ EDT        ┆ EDT        ┆            ┆            ┆           ┆           ┆         │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴─────────┘

## 3.4 Top 10 Sensors by Duration of Flooding Greater Than 12 Inches
Here, we rank sensors and events by total flood duration that's above 12 inches.

In [17]:
sql = """
    SELECT
        sensor_name,
        flood_start_time_est,
        flood_end_time_est,
        duration_mins,
        duration_above_12_inches_mins,
        max_depth_inches,
        tidally_influenced,
        street_name,
        borough
    FROM merged_df
    ORDER BY duration_above_12_inches_mins DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ sensor_nam ┆ flood_sta ┆ flood_end ┆ duration_ ┆ … ┆ max_depth ┆ tidally_i ┆ street_na ┆ borough │
│ e          ┆ rt_time_e ┆ _time_est ┆ mins      ┆   ┆ _inches   ┆ nfluenced ┆ me        ┆ ---     │
│ ---        ┆ st        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str     │
│ str        ┆ ---       ┆ datetime[ ┆ f64       ┆   ┆ f64       ┆ str       ┆ str       ┆         │
│            ┆ datetime[ ┆ μs, Ameri ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ μs, Ameri ┆ ca/New_Yo ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ ca/New_Yo ┆ rk]       ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ rk]       ┆           ┆           ┆   ┆           ┆           ┆           ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ Q -        ┆ 2022-12-2 ┆ 2022-12-2 ┆ 664.96    ┆ … ┆ 40.87     ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆ Court     ┆         │
│ Ct 1       ┆ 05:24:23  ┆ 16:29:21  ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ EST       ┆ EST       ┆           ┆   ┆           ┆           ┆           ┆         │
│ Q -        ┆ 2023-09-2 ┆ 2023-09-2 ┆ 635.44    ┆ … ┆ 15.43     ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 9         ┆ 9         ┆           ┆   ┆           ┆           ┆ Court     ┆         │
│ Ct 1       ┆ 07:11:07  ┆ 17:46:33  ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ EDT       ┆ EDT       ┆           ┆   ┆           ┆           ┆           ┆         │
│ BX -       ┆ 2024-04-0 ┆ 2024-04-0 ┆ 870.27    ┆ … ┆ 34.65     ┆ Yes       ┆ Ditmars   ┆ Bronx   │
│ Ditmars    ┆ 3         ┆ 4         ┆           ┆   ┆           ┆           ┆ Street    ┆         │
│ St/Hunter  ┆ 12:04:19  ┆ 02:34:36  ┆           ┆   ┆           ┆           ┆           ┆         │
│ Ave 2      ┆ EDT       ┆ EDT       ┆           ┆   ┆           ┆           ┆           ┆         │
│ Q -        ┆ 2024-01-1 ┆ 2024-01-1 ┆ 553.46    ┆ … ┆ 34.69     ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆ Court     ┆         │
│ Ct 1       ┆ 08:05:35  ┆ 17:19:03  ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ EST       ┆ EST       ┆           ┆   ┆           ┆           ┆           ┆         │
│ Q -        ┆ 2024-03-0 ┆ 2024-03-1 ┆ 548.48    ┆ … ┆ 20.71     ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 9         ┆ 0         ┆           ┆   ┆           ┆           ┆ Court     ┆         │
│ Ct 1       ┆ 18:52:22  ┆ 05:00:51  ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ EST       ┆ EDT       ┆           ┆   ┆           ┆           ┆           ┆         │
│ Q -        ┆ 2024-04-0 ┆ 2024-04-0 ┆ 537.7     ┆ … ┆ 20.83     ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 4         ┆ 4         ┆           ┆   ┆           ┆           ┆ Court     ┆         │
│ Ct 1       ┆ 02:53:17  ┆ 11:50:59  ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ EDT       ┆ EDT       ┆           ┆   ┆           ┆           ┆           ┆         │
│ Q -        ┆ 2024-03-1 ┆ 2024-03-1 ┆ 467.32    ┆ … ┆ 26.06     ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆ Court     ┆         │
│ Ct 1       ┆ 07:44:49  ┆ 15:32:08  ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ EDT       ┆ EDT       ┆           ┆   ┆           ┆           ┆           ┆         │
│ BX -       ┆ 2024-08-0 ┆ 2024-08-0 ┆ 582.53    ┆ … ┆ 15.75     ┆ Yes       ┆ Ditmars   ┆ Bronx   │
│ Ditmars    ┆ 6         ┆ 7         ┆           ┆   ┆           ┆           ┆ Street    ┆         │
│ St/Hunter  ┆ 17:13:03  ┆ 02:55:34  ┆           ┆   ┆           ┆           ┆           ┆         │
│ Ave 2      ┆ EDT       ┆ EDT       ┆           ┆   ┆           ┆           ┆           ┆         │
│ Q -        ┆ 2024-01-1 ┆ 2024-01-1 ┆ 454.7     ┆ … ┆ 23.94     ┆ Yes       ┆ Davenport ┆ Queens  │
│ Davenport  ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆ Court     ┆         │
│ Ct 1       ┆ 05:39:07  ┆ 13:13:49  ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ EST       ┆ EST       ┆           ┆   ┆           ┆           ┆           ┆         │
│ BX -       ┆ 2024-01-1 ┆ 2024-01-1 ┆ 365.54    ┆ … ┆ 26.02     ┆ Yes       ┆ Ditmars   ┆ Bronx   │
│ Ditmars    ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆ Street    ┆         │
│ St/Hunter  ┆ 09:40:07  ┆ 15:45:39  ┆           ┆   ┆           ┆           ┆           ┆         │
│ Ave 2      ┆ EST       ┆ EST       ┆           ┆   ┆           ┆           ┆           ┆         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

# 4) Average Flood Duration per Event
When flooding occurs at this sensor, how long does a typical event last? This statistic tells you just that.

## 4.1 Top 10 Sensors by Average Flood Duration.

In [18]:
rel = duckdb.sql("""
    SELECT
        sensor_id,
        sensor_name,
        street_name,
        borough,
        tidally_influenced,
        COUNT(sensor_id) AS flood_events,
        SUM(duration_mins) AS duration_mins
    FROM merged_df
    GROUP BY ALL
""")

sql = """
    SELECT
        *,
        duration_mins / flood_events / 60. AS average_duration_hrs
    FROM rel
    ORDER BY average_duration_hrs DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ sensor_id  ┆ sensor_nam ┆ street_nam ┆ borough   ┆ tidally_i ┆ flood_eve ┆ duration_ ┆ average_d │
│ ---        ┆ e          ┆ e          ┆ ---       ┆ nfluenced ┆ nts       ┆ mins      ┆ uration_h │
│ str        ┆ ---        ┆ ---        ┆ str       ┆ ---       ┆ ---       ┆ ---       ┆ rs        │
│            ┆ str        ┆ str        ┆           ┆ str       ┆ i64       ┆ f64       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ BX-cross-s ┆ BX - Cross ┆ Minnieford ┆ Bronx     ┆ Yes       ┆ 9         ┆ 11437.37  ┆ 21.180315 │
│ t-minniefo ┆ St/Minnief ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ rd-ave-1kw ┆ ord Ave    ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ SI-quincy- ┆ SI -       ┆ Quincy     ┆ Staten    ┆ Yes       ┆ 34        ┆ 32593.16  ┆ 15.977039 │
│ ave-iona-s ┆ Quincy     ┆ Avenue,    ┆ Island    ┆           ┆           ┆           ┆           │
│ t-1deh00   ┆ Ave/Iona   ┆ Comanche   ┆           ┆           ┆           ┆           ┆           │
│            ┆ St         ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ BX-1st-st- ┆ BX - 1st   ┆ Avenue A   ┆ Bronx     ┆ No        ┆ 4         ┆ 1899.87   ┆ 7.916125  │
│ avenue-a-1 ┆ St/Avenue  ┆            ┆           ┆           ┆           ┆           ┆           │
│ zby90      ┆ A          ┆            ┆           ┆           ┆           ┆           ┆           │
│ BX-ditmars ┆ BX -       ┆ Ditmars    ┆ Bronx     ┆ Yes       ┆ 1         ┆ 439.45    ┆ 7.324167  │
│ -st-hunter ┆ Ditmars    ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ -ave-1hczk ┆ St/Hunter  ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Ave 1      ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-beach-66 ┆ Q - Beach  ┆ Beach 66th ┆ Queens    ┆ Yes       ┆ 1         ┆ 409.64    ┆ 6.827333  │
│ th-st-thur ┆ 66th       ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ sby-ave-1a ┆ St/Thursby ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Ave        ┆            ┆           ┆           ┆           ┆           ┆           │
│ SI-lenevar ┆ SI -       ┆ Lenevar    ┆ Staten    ┆ No        ┆ 1         ┆ 330.67    ┆ 5.511167  │
│ -ave--drum ┆ Lenevar    ┆ Avenue     ┆ Island    ┆           ┆           ┆           ┆           │
│ goole-rd-w ┆ Ave &      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Drumgoole  ┆            ┆           ┆           ┆           ┆           ┆           │
│            ┆ R…         ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-malcolm ┆ BK -       ┆ Fulton     ┆ Brooklyn  ┆ No        ┆ 1         ┆ 328.97    ┆ 5.482833  │
│ -x-blvd-fu ┆ Fulton St/ ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ lton-st-2m ┆ Malcom X   ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Blvd       ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-9th-st- ┆ BK - 9th   ┆ 9th Street ┆ Brooklyn  ┆ No        ┆ 2         ┆ 632.56    ┆ 5.271333  │
│ smith-st-0 ┆ St/Smith   ┆            ┆           ┆           ┆           ┆           ┆           │
│ etvg0      ┆ St         ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-davenpor ┆ Q -        ┆ Davenport  ┆ Queens    ┆ Yes       ┆ 13        ┆ 3869.63   ┆ 4.961064  │
│ t-ct-2-07z ┆ Davenport  ┆ Court      ┆           ┆           ┆           ┆           ┆           │
│ nk0        ┆ Ct 2       ┆            ┆           ┆           ┆           ┆           ┆           │
│ BX-w-234th ┆ BX -       ┆ Tibbett    ┆ Bronx     ┆ No        ┆ 11        ┆ 3196.52   ┆ 4.843212  │
│ -st-tibbet ┆ Tibbett    ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ t-ave-2cak ┆ Ave/W      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ 234th St   ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## 4.2 Top 10 Sensors by Average Flood Duration for Events Exceeding 12 inches.

In [19]:
rel = duckdb.sql("""
    SELECT
        sensor_id,
        sensor_name,
        street_name,
        borough,
        tidally_influenced,
        COUNT(sensor_id) AS flood_events,
        SUM(duration_above_12_inches_mins) AS duration_above_12_inches_mins
    FROM merged_df
    WHERE duration_above_12_inches_mins > 0
    GROUP BY ALL
""")

sql = """
    SELECT
        *,
        duration_above_12_inches_mins / flood_events / 60. AS average_duration_hrs
    FROM rel
    ORDER BY average_duration_hrs DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬──────────┬────────────┬───────────┬───────────┬───────────┐
│ sensor_id  ┆ sensor_nam ┆ street_nam ┆ borough  ┆ tidally_in ┆ flood_eve ┆ duration_ ┆ average_d │
│ ---        ┆ e          ┆ e          ┆ ---      ┆ fluenced   ┆ nts       ┆ above_12_ ┆ uration_h │
│ str        ┆ ---        ┆ ---        ┆ str      ┆ ---        ┆ ---       ┆ inches_mi ┆ rs        │
│            ┆ str        ┆ str        ┆          ┆ str        ┆ i64       ┆ ns        ┆ ---       │
│            ┆            ┆            ┆          ┆            ┆           ┆ ---       ┆ f64       │
│            ┆            ┆            ┆          ┆            ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪══════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ Q-davenpor ┆ Q -        ┆ Davenport  ┆ Queens   ┆ Yes        ┆ 18        ┆ 4336.86   ┆ 4.015611  │
│ t-ct-1-07z ┆ Davenport  ┆ Court      ┆          ┆            ┆           ┆           ┆           │
│ ks0        ┆ Ct 1       ┆            ┆          ┆            ┆           ┆           ┆           │
│ Q-davenpor ┆ Q -        ┆ Davenport  ┆ Queens   ┆ Yes        ┆ 1         ┆ 208.42    ┆ 3.473667  │
│ t-ct-2-07z ┆ Davenport  ┆ Court      ┆          ┆            ┆           ┆           ┆           │
│ nk0        ┆ Ct 2       ┆            ┆          ┆            ┆           ┆           ┆           │
│ BX-ditmars ┆ BX -       ┆ Ditmars    ┆ Bronx    ┆ Yes        ┆ 11        ┆ 1828.02   ┆ 2.769727  │
│ -st-hunter ┆ Ditmars    ┆ Street     ┆          ┆            ┆           ┆           ┆           │
│ -ave-1kwrk ┆ St/Hunter  ┆            ┆          ┆            ┆           ┆           ┆           │
│ …          ┆ Ave 2      ┆            ┆          ┆            ┆           ┆           ┆           │
│ BK-9th-st- ┆ BK - 9th   ┆ 9th Street ┆ Brooklyn ┆ No         ┆ 2         ┆ 294.42    ┆ 2.4535    │
│ smith-st-0 ┆ St/Smith   ┆            ┆          ┆            ┆           ┆           ┆           │
│ etvg0      ┆ St         ┆            ┆          ┆            ┆           ┆           ┆           │
│ BK-lee-ave ┆ BK - Lee   ┆ Lee Avenue ┆ Brooklyn ┆ No         ┆ 2         ┆ 241.34    ┆ 2.011167  │
│ -middleton ┆ Ave/Middle ┆            ┆          ┆            ┆           ┆           ┆           │
│ -st-19qok0 ┆ ton St     ┆            ┆          ┆            ┆           ┆           ┆           │
│ Q-161st-av ┆ Q - 161st  ┆ 161st      ┆ Queens   ┆ Yes        ┆ 1         ┆ 120.25    ┆ 2.004167  │
│ e-99th-st- ┆ Ave/99th   ┆ Avenue,    ┆          ┆            ┆           ┆           ┆           │
│ 1a5q80     ┆ St         ┆ Grimm      ┆          ┆            ┆           ┆           ┆           │
│            ┆            ┆ Avenue     ┆          ┆            ┆           ┆           ┆           │
│ Q-beach-43 ┆ Q - Beach  ┆ Beach 43rd ┆ Queens   ┆ Yes        ┆ 2         ┆ 217.7     ┆ 1.814167  │
│ rd-st-15qg ┆ 43rd St    ┆ Street     ┆          ┆            ┆           ┆           ┆           │
│ w0         ┆            ┆            ┆          ┆            ┆           ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens   ┆ Yes        ┆ 1         ┆ 106.4     ┆ 1.773333  │
│ le-blvd-ro ┆ Brookville ┆ Boulevard  ┆          ┆            ┆           ┆           ┆           │
│ ckaway-blv ┆ Blvd/      ┆            ┆          ┆            ┆           ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆          ┆            ┆           ┆           ┆           │
│ Q-beach-72 ┆ Q - Beach  ┆ Beach 72nd ┆ Queens   ┆ Yes        ┆ 2         ┆ 204.97    ┆ 1.708083  │
│ nd-st-alme ┆ 72nd       ┆ Street     ┆          ┆            ┆           ┆           ┆           │
│ da-ave-1a5 ┆ St/Almeda  ┆            ┆          ┆            ┆           ┆           ┆           │
│ …          ┆ Ave        ┆            ┆          ┆            ┆           ┆           ┆           │
│ BK-wallabo ┆ BK -       ┆ Wallabout  ┆ Brooklyn ┆ No         ┆ 2         ┆ 196.25    ┆ 1.635417  │
│ ut-st-thro ┆ Wallabout  ┆ Street     ┆          ┆            ┆           ┆           ┆           │
│ op-ave-19q ┆ St/Throop  ┆            ┆          ┆            ┆           ┆           ┆           │
│ …          ┆ Ave        ┆            ┆          ┆            ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴──────────┴────────────┴───────────┴───────────┴───────────┘

# 5) Duration of Flood Events by Total Sensor Duration
Instead of number of events, we normalize by days active of the sensor. This helps us answer questions such as , "On average, how many hours per month does this sensor flood?" What proportion of time is this location flooded?

## Normalize total minutes by days active

In [20]:
deployment_days = duckdb.sql("""
    SELECT
        sensor_id,
        date_diff('day', date_installed, current_date()) AS deployment_days
    FROM metadata_df
""")

flood_events = duckdb.sql("""
    SELECT
        sensor_id,
        sensor_name,
        street_name,
        borough,
        tidally_influenced,
        SUM(duration_mins) AS duration_mins,
    FROM merged_df
    GROUP BY ALL
""")

## 5.1 Total Flood Duration per Month by Tidally Influenced Sensors.

In [21]:
sql = """
    SELECT
        *,
        ROUND((duration_mins / 60. * 30) / deployment_days, 2) AS average_hours_per_month
    FROM flood_events
    JOIN deployment_days USING (sensor_id)
    WHERE tidally_influenced = 'Yes'
    ORDER BY average_hours_per_month DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ sensor_id  ┆ sensor_nam ┆ street_nam ┆ borough   ┆ tidally_i ┆ duration_ ┆ deploymen ┆ average_h │
│ ---        ┆ e          ┆ e          ┆ ---       ┆ nfluenced ┆ mins      ┆ t_days    ┆ ours_per_ │
│ str        ┆ ---        ┆ ---        ┆ str       ┆ ---       ┆ ---       ┆ ---       ┆ month     │
│            ┆ str        ┆ str        ┆           ┆ str       ┆ f64       ┆ i64       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ BX-ditmars ┆ BX -       ┆ Ditmars    ┆ Bronx     ┆ Yes       ┆ 50596.61  ┆ 879       ┆ 28.78     │
│ -st-hunter ┆ Ditmars    ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ -ave-1kwrk ┆ St/Hunter  ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Ave 2      ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-beach-84 ┆ Q - Beach  ┆ Beach 84th ┆ Queens    ┆ Yes       ┆ 66414.81  ┆ 1550      ┆ 21.42     │
│ -st-0me680 ┆ 84 St      ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ SI-quincy- ┆ SI -       ┆ Quincy     ┆ Staten    ┆ Yes       ┆ 32593.16  ┆ 1025      ┆ 15.9      │
│ ave-iona-s ┆ Quincy     ┆ Avenue,    ┆ Island    ┆           ┆           ┆           ┆           │
│ t-1deh00   ┆ Ave/Iona   ┆ Comanche   ┆           ┆           ┆           ┆           ┆           │
│            ┆ St         ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens    ┆ Yes       ┆ 9833.24   ┆ 515       ┆ 9.55      │
│ le-blvd-ro ┆ Brookville ┆ Boulevard  ┆           ┆           ┆           ┆           ┆           │
│ ckaway-blv ┆ Blvd/      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-beach-84 ┆ Q - Beach  ┆ Beach 84th ┆ Queens    ┆ Yes       ┆ 2468.9    ┆ 131       ┆ 9.42      │
│ th-st-beac ┆ 84 St (2)  ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ h-channel- ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-russell- ┆ Q -        ┆ Russell    ┆ Queens    ┆ Yes       ┆ 26554.32  ┆ 1830      ┆ 7.26      │
│ st-1-07zqc ┆ Russell St ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ 0          ┆ 1          ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens    ┆ Yes       ┆ 7037.61   ┆ 515       ┆ 6.83      │
│ le-blvd-ro ┆ Brookville ┆ Boulevard  ┆           ┆           ┆           ┆           ┆           │
│ ckaway-blv ┆ Blvd/      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆           ┆           ┆           ┆           ┆           │
│ BX-cross-s ┆ BX - Cross ┆ Minnieford ┆ Bronx     ┆ Yes       ┆ 11437.37  ┆ 879       ┆ 6.51      │
│ t-minniefo ┆ St/Minnief ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ rd-ave-1kw ┆ ord Ave    ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-brookvil ┆ Q -        ┆ Brookville ┆ Queens    ┆ Yes       ┆ 6188.23   ┆ 515       ┆ 6.01      │
│ le-blvd-14 ┆ Brookville ┆ Boulevard  ┆           ┆           ┆           ┆           ┆           │
│ 9th-ave-3- ┆ Blvd/      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Snake Rd … ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-russell- ┆ Q -        ┆ Russell    ┆ Queens    ┆ Yes       ┆ 17546.76  ┆ 1830      ┆ 4.79      │
│ st-2-07zt4 ┆ Russell St ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ 0          ┆ 2          ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## 5.2 Total Flood Duration per Month by Non-Tidally Influenced Sensors.

In [22]:
sql = """
    SELECT
        *,
        ROUND((duration_mins / 60. * 30) / deployment_days, 2) AS average_hours_per_month
    FROM flood_events
    JOIN deployment_days USING (sensor_id)
    WHERE tidally_influenced = 'No'
    ORDER BY average_hours_per_month DESC
    LIMIT 10
"""

duckdb.sql(sql).pl()

shape: (10, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ sensor_id  ┆ sensor_nam ┆ street_nam ┆ borough   ┆ tidally_i ┆ duration_ ┆ deploymen ┆ average_h │
│ ---        ┆ e          ┆ e          ┆ ---       ┆ nfluenced ┆ mins      ┆ t_days    ┆ ours_per_ │
│ str        ┆ ---        ┆ ---        ┆ str       ┆ ---       ┆ ---       ┆ ---       ┆ month     │
│            ┆ str        ┆ str        ┆           ┆ str       ┆ f64       ┆ i64       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ BX-w-234th ┆ BX -       ┆ Tibbett    ┆ Bronx     ┆ No        ┆ 3196.52   ┆ 347       ┆ 4.61      │
│ -st-tibbet ┆ Tibbett    ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ t-ave-2cak ┆ Ave/W      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ 234th St   ┆            ┆           ┆           ┆           ┆           ┆           │
│ BX-1st-st- ┆ BX - 1st   ┆ Avenue A   ┆ Bronx     ┆ No        ┆ 1899.87   ┆ 599       ┆ 1.59      │
│ avenue-a-1 ┆ St/Avenue  ┆            ┆           ┆           ┆           ┆           ┆           │
│ zby90      ┆ A          ┆            ┆           ┆           ┆           ┆           ┆           │
│ BX-webster ┆ BX -       ┆ Webster    ┆ Bronx     ┆ No        ┆ 1783.25   ┆ 564       ┆ 1.58      │
│ -ave-e-166 ┆ Webster    ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ th-st-2151 ┆ Ave/E      ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ 166th St   ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q-56th-ave ┆ Q - 56th   ┆ 56th       ┆ Queens    ┆ No        ┆ 534.96    ┆ 179       ┆ 1.49      │
│ -springfie ┆ Ave/ Sprin ┆ Avenue     ┆           ┆           ┆           ┆           ┆           │
│ ld-blvd-1z ┆ gfield     ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Blvd       ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-hoyt-st ┆ BK - Hoyt  ┆ Hoyt       ┆ Brooklyn  ┆ No        ┆ 5548.34   ┆ 1981      ┆ 1.4       │
│ -5th-st-00 ┆ St/5th St  ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ 7sk0       ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ SI-haven-a ┆ SI - Haven ┆ Adams      ┆ Staten    ┆ No        ┆ 2070.42   ┆ 770       ┆ 1.34      │
│ ve-adam-av ┆ Ave/ Adam  ┆ Avenue     ┆ Island    ┆           ┆           ┆           ┆           │
│ e-1qijg0   ┆ Ave        ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-malcolm ┆ BK -       ┆ Fulton     ┆ Brooklyn  ┆ No        ┆ 328.97    ┆ 150       ┆ 1.1       │
│ -x-blvd-fu ┆ Fulton St/ ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ lton-st-2m ┆ Malcom X   ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ Blvd       ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-2nd-ave ┆ BK - 2nd   ┆ 2nd Avenue ┆ Brooklyn  ┆ No        ┆ 232.0     ┆ 173       ┆ 0.67      │
│ -49th-st-2 ┆ Ave/49th   ┆            ┆           ┆           ┆           ┆           ┆           │
│ l8qvc      ┆ St         ┆            ┆           ┆           ┆           ┆           ┆           │
│ BK-neptune ┆ BK -       ┆ West 35th  ┆ Brooklyn  ┆ No        ┆ 823.72    ┆ 627       ┆ 0.66      │
│ -ave-w-35t ┆ Neptune    ┆ Street     ┆           ┆           ┆           ┆           ┆           │
│ h-st-1xvfk ┆ Ave W 35th ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ St         ┆            ┆           ┆           ┆           ┆           ┆           │
│ SI-kissel- ┆ SI - Snug  ┆ Snug       ┆ Staten    ┆ No        ┆ 447.98    ┆ 383       ┆ 0.58      │
│ ave-snug-h ┆ Harbor Rd  ┆ Harbor     ┆ Island    ┆           ┆           ┆           ┆           │
│ arbor-rd-2 ┆ / Kissel   ┆ Road       ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ A…         ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

# 6) Quickest Time to X Inches

In [23]:
def time_to_threshold(
    df,
    threshold_inches: float,
    top_n: int = 10,
    ts_sec_col="flood_profile_time_secs",
    ts_in_col="flood_profile_depth_inches",
    max_col="max_depth_inches",
    name_col="sensor_name",
    start_col="flood_start_time_est",
    end_col="flood_end_time_est",
):

    if not isinstance(df, pl.DataFrame):
        df = pl.from_pandas(df)

    if df.is_empty():
        return pl.DataFrame()

    df = df.with_row_index("event_id")

    # Parse list columns
    df = df.with_columns([
        pl.col(ts_sec_col).map_elements(
            lambda x: ast.literal_eval(x) if isinstance(x, str) else x,
            return_dtype=pl.List(pl.Float64),
        ).alias("sec"),

        pl.col(ts_in_col).map_elements(
            lambda x: ast.literal_eval(x) if isinstance(x, str) else x,
            return_dtype=pl.List(pl.Float64),
        ).alias("depth"),
    ])

    # Filter eligible events
    df = df.filter(
        pl.col("sec").is_not_null()
        & pl.col("depth").is_not_null()
        & (pl.col(max_col) >= threshold_inches)
    )

    if df.is_empty():
        return pl.DataFrame()

    # Explode time series
    long = (
        df.select(
            "event_id",
            name_col,
            start_col,
            end_col,
            max_col,
            "sec",
            "depth",
        )
        .explode(["sec", "depth"])
        .with_columns([
            pl.col("sec").cast(pl.Float64),
            pl.col("depth").cast(pl.Float64),
        ])
        .drop_nulls(["sec", "depth"])
    )

    # Normalize time and clamp depth
    long = (
        long
        .with_columns(
            (pl.col("sec") - pl.first("sec").over("event_id")).alias("rel_sec")
        )
        .with_columns(
            pl.when(pl.col("depth") < 0)
            .then(0.0)
            .otherwise(pl.col("depth"))
            .alias("depth")
        )
        .sort(["event_id", "rel_sec"])
    )

    # store full time series
    series_data = (
        long
        .group_by("event_id")
        .agg([
            pl.col("rel_sec").implode().alias("x_values"),
            pl.col("depth").implode().alias("y_values"),
        ])
    )

    # add previous point for interpolation
    long = long.with_columns([
        pl.col("depth").shift(1).over("event_id").alias("prev_depth"),
        pl.col("rel_sec").shift(1).over("event_id").alias("prev_sec"),
        pl.first("depth").over("event_id").alias("start_depth"),
    ])

    # detect crossings
    crossings = long.filter(
        (pl.col("prev_depth") < threshold_inches) &
        (pl.col("depth") >= threshold_inches)
    )

    # interpolate crossing time
    crossings = crossings.with_columns(
        (
            pl.col("prev_sec")
            + (threshold_inches - pl.col("prev_depth"))
            / (pl.col("depth") - pl.col("prev_depth"))
            * (pl.col("rel_sec") - pl.col("prev_sec"))
        ).alias("time_to_thresh_sec")
    )

    # collapse to one row per event
    crossings = (
        crossings
        .group_by("event_id")
        .agg([
            pl.first("time_to_thresh_sec"),
            pl.first("start_depth"),
            pl.first(name_col).alias("name"),
            pl.first(start_col).alias("start"),
            pl.first(end_col).alias("end"),
            pl.first(max_col).alias("depth_max_inches"),
        ])
    )

    if crossings.is_empty():
        return pl.DataFrame()

    crossings = crossings.join(series_data, on="event_id", how="left")

    crossings = crossings.with_columns([
        pl.lit(threshold_inches).alias("threshold_inches"),
        pl.col("time_to_thresh_sec").round(2),
        (pl.col("time_to_thresh_sec") / 60).round(2).alias("time_to_thresh_minutes"),
        (
            (threshold_inches - pl.col("start_depth"))
            / (pl.col("time_to_thresh_sec") / 60)
        ).round(2).alias("rate_to_thresh_in_per_min"),
    ])

    return (
        crossings
        .sort("time_to_thresh_sec")
        .head(top_n)
        .select([
            "name",
            "depth_max_inches",
            "start",
            "end",
            "threshold_inches",
            "time_to_thresh_sec",
            "time_to_thresh_minutes",
            "rate_to_thresh_in_per_min",
            "x_values",
            "y_values",
        ])
    )

## 6.1 Quickest Time to 12 Inches.

In [24]:
threshold_inches = 12

time_to_threshold(
    df=merged_df,
    threshold_inches=threshold_inches
)

shape: (10, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ name      ┆ depth_max ┆ start     ┆ end       ┆ … ┆ time_to_t ┆ rate_to_t ┆ x_values  ┆ y_values │
│ ---       ┆ _inches   ┆ ---       ┆ ---       ┆   ┆ hresh_min ┆ hresh_in_ ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ datetime[ ┆ datetime[ ┆   ┆ utes      ┆ per_min   ┆ list[f64] ┆ list[f64 │
│           ┆ f64       ┆ μs, Ameri ┆ μs, Ameri ┆   ┆ ---       ┆ ---       ┆           ┆ ]        │
│           ┆           ┆ ca/New_Yo ┆ ca/New_Yo ┆   ┆ f64       ┆ f64       ┆           ┆          │
│           ┆           ┆ rk]       ┆ rk]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ BK -      ┆ 31.3      ┆ 2022-09-1 ┆ 2022-09-1 ┆ … ┆ 2.28      ┆ 5.26      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 63.0, …   ┆ 3.46, …  │
│ St/4th Av ┆           ┆ 04:35:09  ┆ 05:21:25  ┆   ┆           ┆           ┆ 2777.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 35.94     ┆ 2023-09-2 ┆ 2023-09-2 ┆ … ┆ 2.92      ┆ 4.11      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 9         ┆ 9         ┆   ┆           ┆           ┆ 63.0, …   ┆ 1.22, …  │
│ St/4th Av ┆           ┆ 07:53:39  ┆ 10:02:50  ┆   ┆           ┆           ┆ 7751.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 35.59     ┆ 2021-09-0 ┆ 2021-09-0 ┆ … ┆ 3.48      ┆ 3.44      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ 312.0, …  ┆ 17.91, … │
│ St/4th Av ┆           ┆ 21:27:16  ┆ 23:11:26  ┆   ┆           ┆           ┆ 6250.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q - 204th ┆ 23.35     ┆ 2025-10-3 ┆ 2025-10-3 ┆ … ┆ 3.91      ┆ 3.07      ┆ [0.0,     ┆ [0.0,    │
│ St/ 100th ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 60.0, …   ┆ 0.98, …  │
│ Ave       ┆           ┆ 16:04:44  ┆ 16:47:45  ┆   ┆           ┆           ┆ 2581.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 17.6      ┆ 2025-10-3 ┆ 2025-10-3 ┆ … ┆ 5.0       ┆ 2.4       ┆ [0.0,     ┆ [0.0,    │
│ Greene    ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 180.0, …  ┆ 6.1, …   │
│ Ave /     ┆           ┆ 15:00:01  ┆ 16:02:01  ┆   ┆           ┆           ┆ 3720.0]   ┆ 0.0]     │
│ Grand Ave ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ SI -      ┆ 21.34     ┆ 2025-07-3 ┆ 2025-07-3 ┆ … ┆ 6.42      ┆ 1.87      ┆ [0.0,     ┆ [0.0,    │
│ Catherine ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ 60.0, …   ┆ 3.35, …  │
│ Ct/Jewett ┆           ┆ 15:40:39  ┆ 16:28:39  ┆   ┆           ┆           ┆ 2880.0]   ┆ 0.0]     │
│ Ave       ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 26.85     ┆ 2021-08-2 ┆ 2021-08-2 ┆ … ┆ 6.86      ┆ 1.75      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆ 311.0, …  ┆ 8.82, …  │
│ St/4th Av ┆           ┆ 00:05:05  ┆ 00:51:45  ┆   ┆           ┆           ┆ 2800.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q -       ┆ 19.96     ┆ 2025-10-3 ┆ 2025-10-3 ┆ … ┆ 7.12      ┆ 1.69      ┆ [0.0,     ┆ [0.0,    │
│ Liberty   ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 120.0, …  ┆ 1.26, …  │
│ Ave/      ┆           ┆ 15:58:49  ┆ 16:45:48  ┆   ┆           ┆           ┆ 2819.0]   ┆ 0.0]     │
│ 183rd St  ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 28.62     ┆ 2021-08-2 ┆ 2021-08-2 ┆ … ┆ 8.59      ┆ 1.4       ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ 311.0, …  ┆ 5.04, …  │
│ St/4th Av ┆           ┆ 21:19:06  ┆ 22:21:20  ┆   ┆           ┆           ┆ 3734.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 12.6      ┆ 2025-10-3 ┆ 2025-10-3 ┆ … ┆ 9.28      ┆ 1.29      ┆ [0.0,     ┆ [0.0,    │
│ Newel     ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 60.0, …   ┆ 2.44, …  │
│ Ave/      ┆           ┆ 15:02:53  ┆ 15:35:53  ┆   ┆           ┆           ┆ 1981.0]   ┆ 0.0]     │
│ Meserole  ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ St        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 6.2 Quickest Time to 24 Inches.

In [25]:
threshold_inches = 24

time_to_threshold(
    df=merged_df,
    threshold_inches=threshold_inches, 
)

shape: (10, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ name      ┆ depth_max ┆ start     ┆ end       ┆ … ┆ time_to_t ┆ rate_to_t ┆ x_values  ┆ y_values │
│ ---       ┆ _inches   ┆ ---       ┆ ---       ┆   ┆ hresh_min ┆ hresh_in_ ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ datetime[ ┆ datetime[ ┆   ┆ utes      ┆ per_min   ┆ list[f64] ┆ list[f64 │
│           ┆ f64       ┆ μs, Ameri ┆ μs, Ameri ┆   ┆ ---       ┆ ---       ┆           ┆ ]        │
│           ┆           ┆ ca/New_Yo ┆ ca/New_Yo ┆   ┆ f64       ┆ f64       ┆           ┆          │
│           ┆           ┆ rk]       ┆ rk]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ BK -      ┆ 31.3      ┆ 2022-09-1 ┆ 2022-09-1 ┆ … ┆ 5.15      ┆ 4.66      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 63.0, …   ┆ 3.46, …  │
│ St/4th Av ┆           ┆ 04:35:09  ┆ 05:21:25  ┆   ┆           ┆           ┆ 2777.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 35.59     ┆ 2021-09-0 ┆ 2021-09-0 ┆ … ┆ 7.99      ┆ 3.0       ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ 312.0, …  ┆ 17.91, … │
│ St/4th Av ┆           ┆ 21:27:16  ┆ 23:11:26  ┆   ┆           ┆           ┆ 6250.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 35.94     ┆ 2023-09-2 ┆ 2023-09-2 ┆ … ┆ 10.33     ┆ 2.32      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 9         ┆ 9         ┆   ┆           ┆           ┆ 63.0, …   ┆ 1.22, …  │
│ St/4th Av ┆           ┆ 07:53:39  ┆ 10:02:50  ┆   ┆           ┆           ┆ 7751.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 26.85     ┆ 2021-08-2 ┆ 2021-08-2 ┆ … ┆ 14.82     ┆ 1.62      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆ 311.0, …  ┆ 8.82, …  │
│ St/4th Av ┆           ┆ 00:05:05  ┆ 00:51:45  ┆   ┆           ┆           ┆ 2800.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 28.62     ┆ 2021-08-2 ┆ 2021-08-2 ┆ … ┆ 18.92     ┆ 1.27      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ 311.0, …  ┆ 5.04, …  │
│ St/4th Av ┆           ┆ 21:19:06  ┆ 22:21:20  ┆   ┆           ┆           ┆ 3734.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK - 9th  ┆ 25.35     ┆ 2023-09-2 ┆ 2023-09-2 ┆ … ┆ 32.04     ┆ 0.75      ┆ [0.0,     ┆ [0.0,    │
│ St/Smith  ┆           ┆ 9         ┆ 9         ┆   ┆           ┆           ┆ 63.0, …   ┆ 3.07, …  │
│ St        ┆           ┆ 07:54:23  ┆ 13:25:16  ┆   ┆           ┆           ┆ 19853.0]  ┆ 0.51]    │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 25.08     ┆ 2023-09-2 ┆ 2023-09-2 ┆ … ┆ 39.53     ┆ 0.61      ┆ [0.0,     ┆ [0.0,    │
│ Wallabout ┆           ┆ 9         ┆ 9         ┆   ┆           ┆           ┆ 63.0, …   ┆ 1.14, …  │
│ St/Throop ┆           ┆ 08:05:49  ┆ 11:03:49  ┆   ┆           ┆           ┆ 10680.0]  ┆ 0.0]     │
│ Ave       ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q -       ┆ 40.87     ┆ 2022-12-2 ┆ 2022-12-2 ┆ … ┆ 39.7      ┆ 0.6       ┆ [0.0,     ┆ [0.0,    │
│ Davenport ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 63.0, …   ┆ 0.79, …  │
│ Ct 1      ┆           ┆ 05:24:23  ┆ 16:29:21  ┆   ┆           ┆           ┆ 39898.0]  ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
│ Q -       ┆ 26.06     ┆ 2024-03-1 ┆ 2024-03-1 ┆ … ┆ 61.46     ┆ 0.39      ┆ [0.0,     ┆ [0.0,    │
│ Davenport ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 126.0, …  ┆ 0.59, …  │
│ Ct 1      ┆           ┆ 07:44:49  ┆ 15:32:08  ┆   ┆           ┆           ┆ 28039.0]  ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q - Beach ┆ 38.19     ┆ 2022-12-2 ┆ 2022-12-2 ┆ … ┆ 62.94     ┆ 0.38      ┆ [0.0,     ┆ [0.0,    │
│ 84 St     ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 127.0, …  ┆ 0.51, …  │
│           ┆           ┆ 05:00:52  ┆ 11:19:11  ┆   ┆           ┆           ┆ 22699.0]  ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 6.3 Quickest Time to 12 Inches for Tidal vs. Non Tidal Sensors.

In [26]:
threshold_inches = 12

# non-tidal sensors
non_tidal_df = merged_df.filter(pl.col("tidally_influenced") == 'No')

time_to_threshold(
    df=non_tidal_df,
    threshold_inches=threshold_inches
)

shape: (10, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ name      ┆ depth_max ┆ start     ┆ end       ┆ … ┆ time_to_t ┆ rate_to_t ┆ x_values  ┆ y_values │
│ ---       ┆ _inches   ┆ ---       ┆ ---       ┆   ┆ hresh_min ┆ hresh_in_ ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ datetime[ ┆ datetime[ ┆   ┆ utes      ┆ per_min   ┆ list[f64] ┆ list[f64 │
│           ┆ f64       ┆ μs, Ameri ┆ μs, Ameri ┆   ┆ ---       ┆ ---       ┆           ┆ ]        │
│           ┆           ┆ ca/New_Yo ┆ ca/New_Yo ┆   ┆ f64       ┆ f64       ┆           ┆          │
│           ┆           ┆ rk]       ┆ rk]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ BK -      ┆ 31.3      ┆ 2022-09-1 ┆ 2022-09-1 ┆ … ┆ 2.28      ┆ 5.26      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 63.0, …   ┆ 3.46, …  │
│ St/4th Av ┆           ┆ 04:35:09  ┆ 05:21:25  ┆   ┆           ┆           ┆ 2777.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 35.94     ┆ 2023-09-2 ┆ 2023-09-2 ┆ … ┆ 2.92      ┆ 4.11      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 9         ┆ 9         ┆   ┆           ┆           ┆ 63.0, …   ┆ 1.22, …  │
│ St/4th Av ┆           ┆ 07:53:39  ┆ 10:02:50  ┆   ┆           ┆           ┆ 7751.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 35.59     ┆ 2021-09-0 ┆ 2021-09-0 ┆ … ┆ 3.48      ┆ 3.44      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ 312.0, …  ┆ 17.91, … │
│ St/4th Av ┆           ┆ 21:27:16  ┆ 23:11:26  ┆   ┆           ┆           ┆ 6250.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q - 204th ┆ 23.35     ┆ 2025-10-3 ┆ 2025-10-3 ┆ … ┆ 3.91      ┆ 3.07      ┆ [0.0,     ┆ [0.0,    │
│ St/ 100th ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 60.0, …   ┆ 0.98, …  │
│ Ave       ┆           ┆ 16:04:44  ┆ 16:47:45  ┆   ┆           ┆           ┆ 2581.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 17.6      ┆ 2025-10-3 ┆ 2025-10-3 ┆ … ┆ 5.0       ┆ 2.4       ┆ [0.0,     ┆ [0.0,    │
│ Greene    ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 180.0, …  ┆ 6.1, …   │
│ Ave /     ┆           ┆ 15:00:01  ┆ 16:02:01  ┆   ┆           ┆           ┆ 3720.0]   ┆ 0.0]     │
│ Grand Ave ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ SI -      ┆ 21.34     ┆ 2025-07-3 ┆ 2025-07-3 ┆ … ┆ 6.42      ┆ 1.87      ┆ [0.0,     ┆ [0.0,    │
│ Catherine ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ 60.0, …   ┆ 3.35, …  │
│ Ct/Jewett ┆           ┆ 15:40:39  ┆ 16:28:39  ┆   ┆           ┆           ┆ 2880.0]   ┆ 0.0]     │
│ Ave       ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 26.85     ┆ 2021-08-2 ┆ 2021-08-2 ┆ … ┆ 6.86      ┆ 1.75      ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 2         ┆ 2         ┆   ┆           ┆           ┆ 311.0, …  ┆ 8.82, …  │
│ St/4th Av ┆           ┆ 00:05:05  ┆ 00:51:45  ┆   ┆           ┆           ┆ 2800.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q -       ┆ 19.96     ┆ 2025-10-3 ┆ 2025-10-3 ┆ … ┆ 7.12      ┆ 1.69      ┆ [0.0,     ┆ [0.0,    │
│ Liberty   ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 120.0, …  ┆ 1.26, …  │
│ Ave/      ┆           ┆ 15:58:49  ┆ 16:45:48  ┆   ┆           ┆           ┆ 2819.0]   ┆ 0.0]     │
│ 183rd St  ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 28.62     ┆ 2021-08-2 ┆ 2021-08-2 ┆ … ┆ 8.59      ┆ 1.4       ┆ [0.0,     ┆ [0.0,    │
│ Carroll   ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ 311.0, …  ┆ 5.04, …  │
│ St/4th Av ┆           ┆ 21:19:06  ┆ 22:21:20  ┆   ┆           ┆           ┆ 3734.0]   ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ BK -      ┆ 12.6      ┆ 2025-10-3 ┆ 2025-10-3 ┆ … ┆ 9.28      ┆ 1.29      ┆ [0.0,     ┆ [0.0,    │
│ Newel     ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 60.0, …   ┆ 2.44, …  │
│ Ave/      ┆           ┆ 15:02:53  ┆ 15:35:53  ┆   ┆           ┆           ┆ 1981.0]   ┆ 0.0]     │
│ Meserole  ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ St        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [27]:
threshold_inches = 12

# tidally influenced sensors
tidal_df = merged_df.filter(pl.col("tidally_influenced") == 'Yes')

time_to_threshold(
    df=tidal_df,
    threshold_inches=threshold_inches
)

shape: (10, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ name      ┆ depth_max ┆ start     ┆ end       ┆ … ┆ time_to_t ┆ rate_to_t ┆ x_values  ┆ y_values │
│ ---       ┆ _inches   ┆ ---       ┆ ---       ┆   ┆ hresh_min ┆ hresh_in_ ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ datetime[ ┆ datetime[ ┆   ┆ utes      ┆ per_min   ┆ list[f64] ┆ list[f64 │
│           ┆ f64       ┆ μs, Ameri ┆ μs, Ameri ┆   ┆ ---       ┆ ---       ┆           ┆ ]        │
│           ┆           ┆ ca/New_Yo ┆ ca/New_Yo ┆   ┆ f64       ┆ f64       ┆           ┆          │
│           ┆           ┆ rk]       ┆ rk]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q - Beach ┆ 23.43     ┆ 2022-12-2 ┆ 2022-12-2 ┆ … ┆ 17.9      ┆ 0.67      ┆ [0.0,     ┆ [0.0,    │
│ 43rd St   ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 252.0, …  ┆ 4.06, …  │
│           ┆           ┆ 06:07:36  ┆ 09:57:30  ┆   ┆           ┆           ┆ 13795.0]  ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
│ Q - 1st   ┆ 16.65     ┆ 2024-03-1 ┆ 2024-03-1 ┆ … ┆ 17.98     ┆ 0.67      ┆ [0.0,     ┆ [0.0,    │
│ St/104th  ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 64.0, …   ┆ 0.63, …  │
│ St        ┆           ┆ 07:57:07  ┆ 13:01:30  ┆   ┆           ┆           ┆ 18264.0]  ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q - Beach ┆ 18.46     ┆ 2024-01-1 ┆ 2024-01-1 ┆ … ┆ 20.82     ┆ 0.58      ┆ [0.0,     ┆ [0.0,    │
│ 43rd St   ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 189.0, …  ┆ 4.72, …  │
│           ┆           ┆ 09:33:00  ┆ 12:16:18  ┆   ┆           ┆           ┆ 9798.0]   ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
│ Q -       ┆ 31.77     ┆ 2022-12-2 ┆ 2022-12-2 ┆ … ┆ 22.01     ┆ 0.55      ┆ [0.0,     ┆ [0.0,    │
│ Russell   ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 63.0, …   ┆ 0.59, …  │
│ St 2      ┆           ┆ 05:12:13  ┆ 11:34:35  ┆   ┆           ┆           ┆ 22943.0]  ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
│ Q -       ┆ 40.87     ┆ 2022-12-2 ┆ 2022-12-2 ┆ … ┆ 24.77     ┆ 0.48      ┆ [0.0,     ┆ [0.0,    │
│ Davenport ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 63.0, …   ┆ 0.79, …  │
│ Ct 1      ┆           ┆ 05:24:23  ┆ 16:29:21  ┆   ┆           ┆           ┆ 39898.0]  ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
│ Q -       ┆ 31.34     ┆ 2022-12-2 ┆ 2022-12-2 ┆ … ┆ 25.34     ┆ 0.47      ┆ [0.0,     ┆ [0.0,    │
│ Russell   ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 303.0, …  ┆ 1.97, …  │
│ St 1      ┆           ┆ 05:10:48  ┆ 11:04:16  ┆   ┆           ┆           ┆ 21208.0]  ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
│ Q - 1st   ┆ 13.7      ┆ 2024-04-0 ┆ 2024-04-0 ┆ … ┆ 25.56     ┆ 0.47      ┆ [0.0,     ┆ [0.0,    │
│ St/104th  ┆           ┆ 4         ┆ 4         ┆   ┆           ┆           ┆ 63.0, …   ┆ 0.51, …  │
│ St        ┆           ┆ 03:00:17  ┆ 08:12:06  ┆   ┆           ┆           ┆ 18709.0]  ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q -       ┆ 17.09     ┆ 2024-03-1 ┆ 2024-03-1 ┆ … ┆ 28.35     ┆ 0.42      ┆ [0.0,     ┆ [0.0,    │
│ Russell   ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆ 63.0, …   ┆ 1.1, …   │
│ St 1      ┆           ┆ 07:35:18  ┆ 12:29:27  ┆   ┆           ┆           ┆ 17649.0]  ┆ 0.0]     │
│           ┆           ┆ EDT       ┆ EDT       ┆   ┆           ┆           ┆           ┆          │
│ Q - 1st   ┆ 12.91     ┆ 2024-03-0 ┆ 2024-03-1 ┆ … ┆ 31.12     ┆ 0.39      ┆ [0.0,     ┆ [0.0,    │
│ St/104th  ┆           ┆ 9         ┆ 0         ┆   ┆           ┆           ┆ 63.0, …   ┆ 0.98, …  │
│ St        ┆           ┆ 19:00:51  ┆ 01:57:58  ┆   ┆           ┆           ┆ 25027.0]  ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
│ Q - Beach ┆ 38.19     ┆ 2022-12-2 ┆ 2022-12-2 ┆ … ┆ 32.13     ┆ 0.37      ┆ [0.0,     ┆ [0.0,    │
│ 84 St     ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 127.0, …  ┆ 0.51, …  │
│           ┆           ┆ 05:00:52  ┆ 11:19:11  ┆   ┆           ┆           ┆ 22699.0]  ┆ 0.0]     │
│           ┆           ┆ EST       ┆ EST       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘